import { WordHintsMap } from '../types';

/**
 * German hints for imposter - Following Three-Filter Rule:
 * 1. Related but not defining
 * 2. Specific in intent but vague in interpretation
 * 3. Never directly reveal the secret word
 */
export const deWordHints: WordHintsMap = {
  // === ANIMALS ===
  elefant: [
    'groß',
    'grau',
    'weise',
    'gedächtnis',
    'majestätisch',
    'rüssel',
    'herde',
    'schwer',
    'sanft',
    'kraft',
  ],
  giraffe: [
    'hoch',
    'flecken',
    'elegant',
    'lange nacken',
    'savanne',
    'blätter',
    'langsam',
    'auge',
    'einzigartig',
    'baumkrone',
  ],
  pinguin: [
    'kalt',
    'schwarz weiß',
    'antarktis',
    'watscheln',
    'fisch',
    'tauchen',
    'gruppe',
    'anzug',
    'niedlich',
    'schnee',
  ],
  delphin: [
    'meerwasser',
    'intelligent',
    'springen',
    'melodisch',
    'freundlich',
    'schnell',
    'gruppe',
    'fische',
    'spielerisch',
    'meerestier',
  ],

  // === FRUITS ===
  apfel: ['rot', 'süß', 'obst', 'kern', 'stamm', 'ernte', 'herbst', 'frisch', 'knackig', 'gesund'],
  banane: [
    'gelb',
    'süß',
    'tropisch',
    'schale',
    'obstsalat',
    'energie',
    'krümm',
    'weich',
    'potassium',
    'affenfutter',
  ],
  orange: [
    'orange farbe',
    'zitrus',
    'saft',
    'vitamin c',
    'süßsauer',
    'frucht',
    'rund',
    'frisch',
    'farbe',
    'winter',
  ],

  // === SPORTS ===
  fussball: [
    'team',
    'tor',
    'ball',
    'netz',
    'fuß',
    'spielfeld',
    'pokal',
    'weltmeister',
    'jubel',
    'tor schuss',
  ],
  basketball: [
    'team',
    'korb',
    'ball',
    'springen',
    'punkte',
    'dribbling',
    'netz',
    'turnhalle',
    'schuss',
    'schnell',
  ],
  tennis: [
    'schläger',
    'ball',
    'netz',
    'platz',
    'aufschlag',
    'punkte',
    'zweier',
    'grün',
    'einzelspiel',
    'kraft',
  ],

  // === OCCUPATIONS ===
  arzt: [
    'krank',
    'hospital',
    'medizin',
    'diagnose',
    'rezept',
    'heilung',
    'vertrauensperson',
    'wissenschaft',
    'krankenschwester',
    'patient',
  ],
  lehrer: [
    'schule',
    'unterricht',
    'bücher',
    'lernen',
    'studieren',
    'klasse',
    'prüfung',
    'wissen',
    'schüler',
    'schulbildung',
  ],
  chef: [
    'restaurant',
    'kochen',
    'menu',
    'geschmack',
    'rezept',
    'gesundheit',
    'fluss',
    'gerichte',
    'präsentation',
    'passion',
  ],

  // === MOVIES ===
  avatar: [
    'blau',
    'alien',
    'pandora',
    'technik',
    'natur',
    'krieg',
    'liebe',
    'zukunft',
    'visuelle effekte',
    'abenteuer',
  ],
  titanic: [
    'schiff',
    'eisberg',
    'tragödie',
    'liebe',
    'first klasse',
    'sinkend',
    'große truhe',
    'ozean',
    'geschichte',
    'herzbrechen',
  ],

  // === FOOD ===
  pizza: [
    'italien',
    'käse',
    'tomate',
    'teig',
    'ofen',
    'schneiden',
    'heiß',
    'lecker',
    'schnell essen',
    'zutaten',
  ],
  burger: [
    'brot',
    'fleisch',
    'salat',
    'senf',
    'schnellimbiss',
    'heiß',
    'hand essen',
    'patty',
    'brötchen',
    'toppings',
  ],

  // === COUNTRIES ===
  deutschland: [
    'mitteleuropa',
    'deutsch',
    'berlin',
    'beer',
    'autobahn',
    'geschichte',
    'kultur',
    'rhein',
    'alpen',
    'industrie',
  ],
  frankreich: [
    'paris',
    'französisch',
    'wein',
    'brot',
    'kultur',
    'liebe',
    'fashion',
    'eiffel',
    'romantisch',
    'kunst',
  ],
  spanien: [
    'madrid',
    'flamenco',
    'paella',
    'siesta',
    'sonne',
    'gitarre',
    'spanisch',
    'mittelmeer',
    'alhambra',
    'fiesta',
  ],

  // === COLORS ===
  rot: [
    'feuer',
    'liebe',
    'wut',
    'wein',
    'blut',
    'rose',
    'traffic stopp',
    'hitze',
    'energie',
    'leidenschaft',
  ],
  blau: [
    'himmel',
    'meer',
    'kalt',
    'traubigkeit',
    'vertrauen',
    'tiefe',
    'frieden',
    'wasser',
    'nacht',
    'frische',
  ],
  grün: [
    'natur',
    'wald',
    'baum',
    'hoffnung',
    'gras',
    'pflanzen',
    'umwelt',
    'wachstum',
    'frische',
    'leben',
  ],

  // === WEATHER ===
  sonne: [
    'wärme',
    'licht',
    'energie',
    'gelb',
    'tag',
    'hitze',
    'tan',
    'himmel',
    'scheinen',
    'morgendämmerung',
  ],
  regen: [
    'nass',
    'wolke',
    'tropfen',
    'grau',
    'schirm',
    'pfütze',
    'wasser',
    'gießen',
    'überschwemmung',
    'depression',
  ],
  schnee: [
    'weiß',
    'kalt',
    'eiskalt',
    'winter',
    'schneeflöckchen',
    'rutschig',
    'schlitten',
    'flocken',
    'frisch',
    'pulver',
  ],

  // === MUSIC ===
  gitarre: [
    'saiten',
    'melodie',
    'zupfen',
    'rock',
    'holz',
    'akkorde',
    'finger',
    'lied',
    'ton',
    'rund',
  ],
  klavier: [
    'weiße schwarze tasten',
    'tasten',
    'musik',
    'klassisch',
    'melodie',
    'harmonie',
    'hände',
    'klassik',
    'noten',
    'elegant',
  ],
};
