import { WordCategory } from '../types';

export const deWordCategories: WordCategory[] = [
  {
    id: 'animals',
    name: 'Tiere',
    emoji: '🐾',
    words: [
      'elefant',
      'giraffe',
      'pinguin',
      'delphin',
      'känguru',
      'oktopus',
      'schmetterling',
      'krokodil',
      'flamingo',
      'igel',
      'koala',
      'leopard',
      'panda',
      'waschbär',
      'zebra',
      'gorilla',
      'gepard',
      'pfau',
      'flusspferd',
      'gürteltier',
      'adler',
      'hai',
      'schildkröte',
      'chamäleon',
      'wolf',
      'bär',
      'löwe',
      'tiger',
      'schlange',
      'eule',
      'wal',
      'nashorn',
      'strauß',
      'biber',
      'fledermaus',
      'biene',
      'spinne',
      'krebs',
      'qualle',
      'pferd',
      'kaninchen',
      'maus',
      'katze',
      'hund',
    ],
  },
  {
    id: 'fruits',
    name: 'Obst',
    emoji: '🍎',
    words: [
      'apfel',
      'banane',
      'orange',
      'erdbeere',
      'zitrone',
      'wassermelone',
      'ananas',
      'traube',
      'kirsche',
      'pfirsich',
      'birne',
      'himbeere',
      'brombeere',
      'blaubeere',
      'kiwi',
      'mango',
      'kokosnuss',
      'avocado',
      'papaya',
      'granatapfel',
      'feige',
      'aprikose',
      'pflaume',
      'grapefruit',
      'mandarine',
    ],
  },
  {
    id: 'sports',
    name: 'Sport',
    emoji: '⚽',
    words: [
      'fussball',
      'basketball',
      'tennis',
      'volleyball',
      'eishockey',
      'golf',
      'boxen',
      'ringen',
      'schwimmen',
      'laufen',
      'radfahren',
      'skateboarden',
      'surfen',
      'skifahren',
      'snowboarden',
      'eislaufen',
      'gymnastik',
      'klettern',
      'badminton',
      'tischtennis',
      'dart',
      'billard',
      'bowling',
      'reiten',
      'judo',
    ],
  },
  {
    id: 'occupations',
    name: 'Berufe',
    emoji: '💼',
    words: [
      'arzt',
      'krankenschwester',
      'lehrer',
      'ingenieur',
      'anwalt',
      'zahnarzt',
      'friseur',
      'chef',
      'polizist',
      'feuerwehrmann',
      'pilot',
      'bäcker',
      'fotografer',
      'maler',
      'architekt',
      'wissenschaftler',
      'farmer',
      'mechaniker',
      'klempner',
      'elektriker',
      'kellner',
      'koch',
      'bauer',
      'hirte',
      'jäger',
    ],
  },
  {
    id: 'movies',
    name: 'Filme',
    emoji: '🎬',
    words: [
      'avatar',
      'titanic',
      'harrry potter',
      'starwars',
      'herr der ringe',
      'jaws',
      'jurassic park',
      'et',
      'der weiße hai',
      'back to the future',
      'ghostbusters',
      'matrix',
      'twisters',
      'inception',
      'interstellar',
      'das shining',
      'die fliege',
      'der berg',
      'der tennisplatz',
      'godzilla',
      'king kong',
      'die mumie',
      'halloween',
      'freitag der 13',
      'nightmare on elm street',
    ],
  },
  {
    id: 'food',
    name: 'Lebensmittel',
    emoji: '🍕',
    words: [
      'pizza',
      'burger',
      'pasta',
      'brot',
      'käse',
      'schinken',
      'salat',
      'suppe',
      'nudeln',
      'kartoffel',
      'mais',
      'bohne',
      'erbse',
      'karotte',
      'tomate',
      'zwiebel',
      'knoblauch',
      'fisch',
      'hähnchen',
      'rind',
      'schwein',
      'schaf',
      'eier',
      'butter',
      'milch',
    ],
  },
  {
    id: 'countries',
    name: 'Länder',
    emoji: '🌍',
    words: [
      'deutschland',
      'frankreich',
      'spanien',
      'italien',
      'england',
      'polen',
      'schweden',
      'norwegen',
      'dänemark',
      'niederlande',
      'belgien',
      'schweiz',
      'österreich',
      'tschechien',
      'ungarn',
      'rumänien',
      'bulgarien',
      'griechenland',
      'portugal',
      'irland',
      'schottland',
      'wales',
      'japan',
      'china',
      'indien',
    ],
  },
  {
    id: 'colors',
    name: 'Farben',
    emoji: '🌈',
    words: [
      'rot',
      'blau',
      'grün',
      'gelb',
      'orange',
      'lila',
      'rosa',
      'braun',
      'grau',
      'schwarz',
      'weiß',
      'türkis',
      'gold',
      'silber',
      'marineblau',
      'dunkelgrün',
      'hellblau',
      'dunkelrot',
      'creme',
      'beige',
      'karminrot',
      'magenta',
      'cyan',
      'khaki',
      'olive',
    ],
  },
  {
    id: 'weather',
    name: 'Wetter',
    emoji: '⛅',
    words: [
      'sonne',
      'regen',
      'schnee',
      'wind',
      'wolke',
      'sturm',
      'blitz',
      'donner',
      'hagel',
      'nebel',
      'tau',
      'regenbogen',
      'wirbelsturm',
      'tornado',
      'zyklon',
      'gewitter',
      'frost',
      'eis',
      'trockenheit',
      'hitze',
      'kälte',
      'brise',
      'böe',
      'nieselregen',
      'platzregen',
    ],
  },
  {
    id: 'music',
    name: 'Musik',
    emoji: '🎵',
    words: [
      'gitarre',
      'klavier',
      'trompete',
      'schlagzeug',
      'violine',
      'flöte',
      'saxophon',
      'orgel',
      'harfe',
      'mandoline',
      'banjo',
      'oboe',
      'klarinette',
      'posaune',
      'horn',
      'cello',
      'kontrabass',
      'akkordeon',
      'mundharmonika',
      'metronom',
      'dirigent',
      'noten',
      'melodie',
      'harmonie',
      'rhythmus',
    ],
  },
];
