import { WordHintsMap } from '../types';

/**
 * English hints for imposter - Following Three-Filter Rule:
 * 1. Related but not defining
 * 2. Specific in intent but vague in interpretation
 * 3. Never directly reveal the secret word
 *
 * Hints are experiences, emotions, or abstract concepts - NOT synonyms,
 * translations, direct categories, or physical components.
 */
export const enWordHints: WordHintsMap = {
  // === ANIMALS ===
  'elephant': ['heavy', 'wise', 'gray', 'memory', 'majestic'],
  'giraffe': ['tall', 'spotted', 'elegant', 'calm', 'curious'],
  'penguin': ['cold', 'elegant', 'clumsy', 'family', 'tuxedo'],
  'dolphin': ['intelligent', 'playful', 'jumps', 'friendly', 'marine'],
  'kangaroo': ['jumping', 'pouch', 'australia', 'muscular', 'protective'],
  'octopus': ['flexible', 'intelligent', 'mysterious', 'hidden', 'deep'],
  'butterfly': ['transformation', 'delicate', 'colorful', 'fleeting', 'free'],
  'crocodile': ['patient', 'ancient', 'dangerous', 'silent', 'ambush'],
  'flamingo': ['pink', 'elegant', 'balance', 'tropical', 'flock'],
  'hedgehog': ['defensive', 'small', 'nocturnal', 'shy', 'ball'],
  'koala': ['sleepy', 'cuddly', 'slow', 'australia', 'hugging'],
  'leopard': ['spotted', 'stealthy', 'fast', 'solitary', 'nocturnal'],
  'panda': ['cuddly', 'calm', 'bamboo', 'rare', 'gentle'],
  'raccoon': ['mischievous', 'nocturnal', 'curious', 'masked', 'clever'],
  'zebra': ['stripes', 'herd', 'fast', 'african', 'unique'],
  'gorilla': ['strong', 'family', 'intelligent', 'protective', 'imposing'],
  'cheetah': ['speed', 'spotted', 'african', 'elegant', 'solitary'],
  'peacock': ['showy', 'colorful', 'display', 'proud', 'garden'],
  'hippopotamus': ['heavy', 'aquatic', 'territorial', 'dangerous', 'large'],
  'armadillo': ['armored', 'digger', 'nocturnal', 'shy', 'ball'],
  'eagle': ['free', 'sharp vision', 'majestic', 'heights', 'powerful'],
  'shark': ['feared', 'ancient', 'solitary', 'hunter', 'deep'],
  'turtle': ['slow', 'long-lived', 'patient', 'protected', 'wise'],
  'chameleon': ['change', 'adaptable', 'patient', 'observer', 'unique'],
  'wolf': ['pack', 'howl', 'loyal', 'nocturnal', 'wild'],
  'bear': ['hibernation', 'strong', 'solitary', 'protective', 'forest'],
  'lion': ['proud', 'leader', 'majestic', 'family', 'savanna'],
  'tiger': ['stripes', 'solitary', 'powerful', 'stealthy', 'orange'],
  'snake': ['silent', 'flexible', 'cold', 'hypnotic', 'shedding'],
  'owl': ['nocturnal', 'wise', 'silent', 'rotating', 'observer'],

  // === FOOD ===
  'pizza': ['sharing', 'party', 'round', 'hot', 'favorite'],
  'hamburger': ['quick', 'juicy', 'american', 'satisfying', 'layers'],
  'spaghetti': ['twirl', 'italian', 'long', 'romantic', 'traditional'],
  'sushi': ['fresh', 'art', 'japanese', 'delicate', 'raw'],
  'tacos': ['party', 'mexican', 'spicy', 'filled', 'crunchy'],
  'pancakes': ['breakfast', 'fluffy', 'sweet', 'sunday', 'family'],
  'chocolate': ['temptation', 'sweet', 'gift', 'comfort', 'melted'],
  'watermelon': ['summer', 'refreshing', 'seeds', 'red', 'juicy'],
  'pineapple': ['tropical', 'tangy', 'spiky', 'exotic', 'yellow'],
  'avocado': ['creamy', 'healthy', 'green', 'trendy', 'toast'],
  'croissant': ['french', 'flaky', 'buttery', 'breakfast', 'coffee'],
  'burrito': ['rolled', 'filling', 'mexican', 'stuffed', 'large'],
  'lasagna': ['layers', 'italian', 'baked', 'family', 'hearty'],
  'cake': ['celebration', 'sweet', 'birthday', 'decorated', 'candles'],
  'pretzel': ['twisted', 'salty', 'german', 'crunchy', 'festival'],
  'popcorn': ['movies', 'crunchy', 'salty', 'sharing', 'cinema'],
  'empanada': ['filled', 'golden', 'warm', 'homemade', 'tradition'],
  'waffle': ['grid', 'breakfast', 'belgian', 'sweet', 'crispy'],
  'sandwich': ['quick', 'practical', 'layers', 'lunch', 'picnic'],
  'nachos': ['crunchy', 'sharing', 'mexican', 'party', 'melted'],
  'paella': ['spanish', 'yellow', 'family', 'sunday', 'festive'],
  'ceviche': ['fresh', 'tangy', 'peruvian', 'seafood', 'spicy'],
  'doughnut': ['sweet', 'round', 'glazed', 'coffee', 'treat'],
  'churros': ['sweet', 'spanish', 'crispy', 'fair', 'dipping'],
  'ice cream': ['cold', 'summer', 'creamy', 'sweet', 'melting'],
  'pudding': ['soft', 'caramel', 'wobbly', 'dessert', 'creamy'],
  'salad': ['fresh', 'healthy', 'green', 'crunchy', 'light'],
  'soup': ['warm', 'comforting', 'winter', 'homemade', 'spoon'],
  'rice': ['basic', 'versatile', 'asian', 'white', 'side dish'],
  'chicken': ['versatile', 'family', 'sunday', 'affordable', 'common'],

  // === PLACES ===
  'beach': ['relaxing', 'summer', 'sandy', 'vacation', 'horizon'],
  'mountain': ['challenging', 'fresh air', 'height', 'adventure', 'silence'],
  'library': ['quiet', 'knowledge', 'peaceful', 'concentration', 'order'],
  'hospital': ['sterile', 'worry', 'hope', 'urgent', 'care'],
  'airport': ['waiting', 'goodbyes', 'early morning', 'luggage', 'nerves'],
  'museum': ['history', 'quiet', 'admiration', 'culture', 'ancient'],
  'stadium': ['excitement', 'crowd', 'cheering', 'passion', 'victory'],
  'restaurant': ['celebration', 'service', 'waiting', 'elegant', 'date'],
  'casino': ['luck', 'risk', 'lights', 'nighttime', 'temptation'],
  'zoo': ['family', 'educational', 'enclosed', 'watching', 'weekend'],
  'park': ['family', 'stroll', 'green', 'children', 'relaxation'],
  'cinema': ['dark', 'popcorn', 'escape', 'quiet', 'screen'],
  'theater': ['dramatic', 'elegant', 'applause', 'culture', 'curtain'],
  'church': ['quiet', 'peace', 'reflection', 'sunday', 'community'],
  'supermarket': ['list', 'comparing', 'carts', 'routine', 'line'],
  'school': ['learning', 'friends', 'routine', 'bell', 'memories'],
  'university': ['freedom', 'exams', 'future', 'independence', 'studying'],
  'gym': ['effort', 'sweat', 'discipline', 'mirrors', 'routine'],
  'pool': ['refreshing', 'summer', 'chlorine', 'diving', 'floating'],
  'garden': ['peace', 'colors', 'care', 'spring', 'fragrance'],
  'plaza': ['meeting', 'community', 'resting', 'pigeons', 'center'],
  'market': ['bustling', 'colors', 'fresh', 'bargaining', 'aromas'],
  'station': ['waiting', 'arrivals', 'goodbyes', 'schedules', 'travelers'],
  'harbor': ['salty smell', 'commerce', 'seagulls', 'horizon', 'departures'],
  'lighthouse': ['guidance', 'lonely', 'nighttime', 'tall', 'safety'],
  'castle': ['medieval', 'mysterious', 'stone', 'historic', 'fantasy'],
  'palace': ['luxury', 'grand', 'historic', 'elegant', 'power'],
  'pyramid': ['ancient', 'mysterious', 'triangular', 'monumental', 'desert'],
  'cave': ['dark', 'cold', 'mysterious', 'echo', 'exploring'],
  'volcano': ['dangerous', 'powerful', 'hot', 'dormant', 'imposing'],

  // === PROFESSIONS ===
  'doctor': ['white coat', 'caring', 'trust', 'studying', 'calling'],
  'firefighter': ['brave', 'emergency', 'siren', 'hero', 'red'],
  'astronaut': ['adventure', 'training', 'isolated', 'pioneer', 'dream'],
  'chef': ['creative', 'pressure', 'flavors', 'passion', 'heat'],
  'pilot': ['responsibility', 'travel', 'uniform', 'altitude', 'control'],
  'teacher': ['patience', 'calling', 'influence', 'board', 'future'],
  'detective': ['observant', 'curious', 'logical', 'mystery', 'clues'],
  'architect': ['vision', 'creative', 'blueprints', 'spaces', 'design'],
  'surgeon': ['precision', 'pressure', 'steady hands', 'concentration', 'long hours'],
  'musician': ['expressive', 'practice', 'emotional', 'talent', 'stage'],
  'lawyer': ['arguments', 'formal', 'defense', 'justice', 'words'],
  'police officer': ['protection', 'order', 'uniform', 'community', 'patrol'],
  'veterinarian': ['compassionate', 'animals', 'caring', 'calling', 'patience'],
  'journalist': ['curious', 'fast', 'truth', 'news', 'investigating'],
  'engineer': ['analytical', 'solutions', 'logical', 'building', 'calculating'],
  'dentist': ['precision', 'hygiene', 'nerves', 'smiles', 'checkup'],
  'nurse': ['caring', 'night shift', 'compassion', 'exhausting', 'dedicated'],
  'photographer': ['observant', 'moment', 'light', 'creativity', 'perspective'],
  'painter': ['creative', 'colors', 'expressive', 'solitary', 'inspiration'],
  'actor': ['versatile', 'emotional', 'memorizing', 'nerves', 'applause'],
  'singer': ['emotional', 'stage', 'rehearsal', 'nerves', 'microphone'],
  'dancer': ['discipline', 'grace', 'physical', 'expressive', 'rehearsal'],
  'writer': ['solitary', 'imaginative', 'observant', 'discipline', 'coffee'],
  'scientist': ['curious', 'methodical', 'patient', 'discovery', 'laboratory'],
  'programmer': ['logical', 'nocturnal', 'problem', 'coffee', 'creative'],
  'mechanic': ['practical', 'greasy', 'diagnosis', 'tools', 'fixing'],
  'electrician': ['careful', 'technical', 'wires', 'dangerous', 'fixing'],
  'carpenter': ['traditional', 'wood', 'measuring', 'creative', 'tools'],
  'baker': ['early morning', 'aroma', 'warmth', 'traditional', 'dough'],
  'gardener': ['patient', 'nature', 'seasons', 'caring', 'peaceful'],

  // === MOVIES ===
  'titanic': ['tragic', 'romantic', 'cold', 'unforgettable', 'classic'],
  'avatar': ['fantastical', 'blue', 'nature', 'technology', 'otherworldly'],
  'frozen': ['cold', 'musical', 'sisters', 'magic', 'freedom'],
  'jaws': ['fear', 'summer', 'water', 'suspense', 'classic'],
  'batman': ['dark', 'nocturnal', 'justice', 'lonely', 'revenge'],
  'shrek': ['different', 'humor', 'friendship', 'swamp', 'layers'],
  'inception': ['confusing', 'dreams', 'labyrinth', 'deep', 'twist'],
  'gladiator': ['epic', 'revenge', 'arena', 'honor', 'ancient'],
  'matrix': ['philosophical', 'reality', 'choice', 'revolutionary', 'black'],
  'coco': ['family', 'music', 'tradition', 'colorful', 'memories'],
  'up': ['adventure', 'emotional', 'dreams', 'balloons', 'friendship'],
  'ratatouille': ['aspirations', 'cooking', 'small', 'dreams', 'france'],
  'toy story': ['childhood', 'friendship', 'nostalgia', 'loyalty', 'adventure'],
  'finding nemo': ['family', 'ocean', 'adventure', 'perseverance', 'colorful'],
  'cars': ['speed', 'friendship', 'humility', 'rural', 'racing'],
  'moana': ['ocean', 'adventure', 'identity', 'brave', 'musical'],
  'encanto': ['family', 'magic', 'unique', 'musical', 'colombian'],
  'spider-man': ['responsibility', 'young', 'city', 'secret', 'agile'],
  'iron man': ['technology', 'genius', 'arrogant', 'transformation', 'metal'],
  'thor': ['mythology', 'power', 'family', 'hero', 'nordic'],
  'jurassic park': ['prehistoric', 'danger', 'science', 'adventure', 'island'],
  'harry potter': ['magic', 'friendship', 'destiny', 'mystery', 'school'],
  'star wars': ['epic', 'family', 'destiny', 'galaxy', 'classic'],
  'the godfather': ['family', 'power', 'loyalty', 'dark', 'classic'],
  'forrest gump': ['innocent', 'historical', 'running', 'destiny', 'love'],
  'rocky': ['effort', 'underdog', 'inspiring', 'training', 'fight'],
  'rambo': ['survival', 'loner', 'jungle', 'action', 'trauma'],
  'terminator': ['future', 'unstoppable', 'metal', 'chase', 'destiny'],
  'alien': ['horror', 'isolated', 'dark', 'survival', 'space'],
  'indiana jones': ['adventure', 'archaeology', 'danger', 'hat', 'classic'],

  // === SPORTS ===
  'soccer': ['passion', 'global', 'team', 'sunday', 'goals'],
  'basketball': ['tall', 'fast', 'court', 'american', 'jumping'],
  'tennis': ['elegant', 'individual', 'concentration', 'white', 'rally'],
  'swimming': ['refreshing', 'breathing', 'discipline', 'early morning', 'pool'],
  'baseball': ['american', 'slow', 'stadium', 'summer', 'family'],
  'volleyball': ['beach', 'team', 'jumping', 'summer', 'net'],
  'golf': ['patience', 'quiet', 'green', 'exclusive', 'peaceful'],
  'boxing': ['intense', 'discipline', 'one on one', 'sweat', 'ring'],
  'cycling': ['endurance', 'scenery', 'freedom', 'speed', 'hills'],
  'athletics': ['basic', 'speed', 'track', 'records', 'effort'],
  'surfing': ['freedom', 'waves', 'balance', 'summer', 'californian'],
  'skiing': ['cold', 'speed', 'winter', 'mountain', 'white'],
  'skating': ['grace', 'balance', 'ice', 'elegant', 'spins'],
  'karate': ['discipline', 'respect', 'eastern', 'belt', 'control'],
  'judo': ['throws', 'respect', 'grip', 'eastern', 'mat'],
  'hockey': ['cold', 'fast', 'team', 'canadian', 'intense'],
  'rugby': ['physical', 'team', 'mud', 'respect', 'oval'],
  'cricket': ['english', 'slow', 'tradition', 'elegant', 'summer'],
  'badminton': ['fast', 'feather', 'light', 'asian', 'reflexes'],
  'ping pong': ['fast', 'reflexes', 'small', 'asian', 'indoor'],
  'climbing': ['vertical', 'strength', 'mental', 'adventure', 'grips'],
  'skydiving': ['adrenaline', 'falling', 'freedom', 'courage', 'sky'],
  'diving': ['silence', 'deep', 'breathing', 'colors', 'peace'],
  'sailing': ['wind', 'freedom', 'patience', 'horizon', 'quiet'],
  'rowing': ['rhythm', 'team', 'early morning', 'water', 'synchronized'],
  'gymnastics': ['flexibility', 'grace', 'perfection', 'discipline', 'young'],
  'wrestling': ['ancient', 'strength', 'tradition', 'contact', 'olympic'],
  'fencing': ['elegant', 'strategy', 'fast', 'tradition', 'white'],
  'polo': ['exclusive', 'speed', 'elegant', 'green', 'tradition'],
  'horseback riding': ['elegant', 'connection', 'discipline', 'tradition', 'countryside'],

  // === OBJECTS ===
  'phone': ['addictive', 'communication', 'constant', 'personal', 'distraction'],
  'computer': ['work', 'connection', 'information', 'modern', 'screen'],
  'television': ['entertainment', 'passive', 'family', 'news', 'couch'],
  'clock': ['routine', 'punctual', 'anxiety', 'gift', 'elegant'],
  'lamp': ['ambiance', 'nighttime', 'reading', 'decorative', 'warm'],
  'chair': ['rest', 'common', 'office', 'waiting', 'meeting'],
  'table': ['gathering', 'family', 'work', 'eating', 'central'],
  'bed': ['rest', 'dreams', 'comfort', 'intimate', 'soft'],
  'mirror': ['reflection', 'vanity', 'truth', 'morning', 'decorative'],
  'window': ['light', 'outside', 'air', 'watching', 'escape'],
  'door': ['opportunity', 'privacy', 'entrance', 'closing', 'security'],
  'stairs': ['effort', 'ascending', 'stages', 'building', 'exercise'],
  'elevator': ['waiting', 'small', 'fast', 'awkward', 'modern'],
  'bicycle': ['freedom', 'exercise', 'ecological', 'childhood', 'balance'],
  'car': ['independence', 'travel', 'traffic', 'freedom', 'expensive'],
  'airplane': ['distance', 'fast', 'nerves', 'altitude', 'window seat'],
  'boat': ['slow', 'horizon', 'seasick', 'vacation', 'romantic'],
  'train': ['journey', 'scenery', 'punctual', 'nostalgic', 'rhythm'],
  'motorcycle': ['freedom', 'adrenaline', 'young', 'fast', 'wind'],
  'skateboard': ['young', 'urban', 'tricks', 'rebellious', 'balance'],
  'guitar': ['romantic', 'campfire', 'expressive', 'learning', 'acoustic'],
  'piano': ['elegant', 'classical', 'dedication', 'large', 'expressive'],
  'drums': ['rhythm', 'primitive', 'party', 'energy', 'tribal'],
  'violin': ['emotional', 'classical', 'difficult', 'orchestra', 'elegant'],
  'flute': ['sweet', 'ancient', 'school', 'breath', 'melody'],
  'camera': ['memories', 'moment', 'travel', 'observing', 'capturing'],
  'book': ['escape', 'knowledge', 'imagination', 'quiet', 'old'],
  'pencil': ['ideas', 'school', 'erasing', 'simple', 'creative'],
  'scissors': ['cutting', 'precise', 'crafts', 'dangerous', 'school'],
  'umbrella': ['protection', 'rain', 'forgotten', 'city', 'gray'],

  // === NATURE ===
  'tree': ['shade', 'ancient', 'growth', 'roots', 'home'],
  'flower': ['gift', 'fleeting', 'fragrance', 'spring', 'romantic'],
  'river': ['flowing', 'constant', 'border', 'life', 'journey'],
  'lake': ['calm', 'reflection', 'deep', 'mysterious', 'silence'],
  'ocean': ['vast', 'mysterious', 'powerful', 'horizon', 'deep'],
  'forest': ['peace', 'mysterious', 'green', 'refuge', 'ancient'],
  'jungle': ['dense', 'humid', 'wild', 'noisy', 'dangerous'],
  'desert': ['empty', 'heat', 'solitude', 'extreme', 'golden'],
  'island': ['isolated', 'escape', 'tropical', 'small', 'paradise'],
  'waterfall': ['powerful', 'noisy', 'fresh', 'majestic', 'adventure'],
  'rainbow': ['hope', 'fleeting', 'magical', 'after rain', 'colors'],
  'cloud': ['soft', 'shapes', 'white', 'changing', 'dreaming'],
  'sun': ['energy', 'warmth', 'waking', 'life', 'bright'],
  'moon': ['nocturnal', 'romantic', 'cycles', 'mysterious', 'silver'],
  'star': ['wish', 'distant', 'nocturnal', 'bright', 'navigation'],
  'rain': ['melancholy', 'cleansing', 'sound', 'gray', 'refreshing'],
  'snow': ['silence', 'cold', 'white', 'christmas', 'pure'],
  'thunder': ['fear', 'powerful', 'warning', 'noise', 'storm'],
  'lightning': ['fast', 'dangerous', 'bright', 'energy', 'fleeting'],
  'tornado': ['destructive', 'spinning', 'fear', 'powerful', 'chaotic'],
  'earthquake': ['fear', 'destructive', 'unpredictable', 'shaking', 'panic'],
  'tsunami': ['destructive', 'giant', 'panic', 'coastal', 'fast'],
  'glacier': ['ancient', 'cold', 'slow', 'blue', 'melting'],
  'aurora': ['magical', 'nocturnal', 'northern', 'colorful', 'fleeting'],
  'sunrise': ['new', 'hope', 'early', 'orange', 'beginning'],
  'sunset': ['romantic', 'orange', 'peaceful', 'ending', 'contemplation'],
  'coral': ['colorful', 'fragile', 'underwater', 'colony', 'protected'],
  'seaweed': ['green', 'slippery', 'marine', 'food', 'tangled'],
  'mushroom': ['dark', 'damp', 'mysterious', 'forest', 'quick'],
  'cactus': ['resilient', 'spiny', 'dry', 'green', 'lonely']
};
