import { WordHintsMap } from '../types';

/**
 * Spanish hints for imposter - Following Three-Filter Rule:
 * 1. Related but not defining
 * 2. Specific in intent but vague in interpretation
 * 3. Never directly reveal the secret word
 *
 * Hints are experiences, emotions, or abstract concepts - NOT synonyms,
 * translations, direct categories, or physical components.
 */
export const esWordHints: WordHintsMap = {
  // === ANIMALS ===
  'elefante': ['pesado', 'sabio', 'gris', 'memoria', 'majestuoso'],
  'jirafa': ['alto', 'manchado', 'elegante', 'tranquilo', 'curioso'],
  'pingüino': ['frío', 'elegante', 'torpe', 'familia', 'blanco y negro'],
  'delfín': ['inteligente', 'juguetón', 'saltos', 'amigable', 'marino'],
  'canguro': ['saltos', 'bolsa', 'australia', 'musculoso', 'protector'],
  'pulpo': ['flexible', 'inteligente', 'misterioso', 'escondido', 'profundo'],
  'mariposa': ['transformación', 'delicado', 'colorido', 'efímero', 'libre'],
  'cocodrilo': ['paciente', 'antiguo', 'peligroso', 'silencioso', 'emboscada'],
  'flamenco': ['rosa', 'elegante', 'equilibrio', 'tropical', 'grupo'],
  'erizo': ['defensivo', 'pequeño', 'nocturno', 'tímido', 'bola'],
  'koala': ['dormilón', 'tierno', 'lento', 'australia', 'abrazo'],
  'leopardo': ['manchas', 'sigiloso', 'veloz', 'solitario', 'nocturno'],
  'panda': ['tierno', 'tranquilo', 'bambú', 'raro', 'gentil'],
  'mapache': ['travieso', 'nocturno', 'curioso', 'antifaz', 'astuto'],
  'cebra': ['rayas', 'manada', 'veloz', 'africano', 'único'],
  'gorila': ['fuerte', 'familiar', 'inteligente', 'protector', 'imponente'],
  'guepardo': ['velocidad', 'manchas', 'africano', 'elegante', 'solitario'],
  'pavo real': ['presumido', 'colorido', 'exhibición', 'orgulloso', 'jardín'],
  'hipopótamo': ['pesado', 'acuático', 'territorial', 'peligroso', 'grande'],
  'armadillo': ['blindado', 'excavador', 'nocturno', 'tímido', 'bola'],
  'águila': ['libre', 'vista aguda', 'majestuoso', 'altura', 'poderoso'],
  'tiburón': ['temido', 'antiguo', 'solitario', 'cazador', 'profundo'],
  'tortuga': ['lento', 'longevo', 'paciente', 'protegido', 'sabio'],
  'camaleón': ['cambio', 'adaptable', 'paciente', 'observador', 'único'],
  'lobo': ['manada', 'aullido', 'leal', 'nocturno', 'salvaje'],
  'oso': ['hibernación', 'fuerte', 'solitario', 'protector', 'bosque'],
  'león': ['orgulloso', 'líder', 'majestuoso', 'familia', 'sabana'],
  'tigre': ['rayas', 'solitario', 'poderoso', 'sigiloso', 'naranja'],
  'serpiente': ['silencioso', 'flexible', 'frío', 'hipnótico', 'muda'],
  'búho': ['nocturno', 'sabio', 'silencioso', 'giratorio', 'observador'],

  // === FOOD ===
  'pizza': ['compartir', 'fiesta', 'redondo', 'caliente', 'favorito'],
  'hamburguesa': ['rápido', 'jugoso', 'americano', 'satisfactorio', 'capas'],
  'espagueti': ['enrollar', 'italiano', 'largo', 'romántico', 'tradicional'],
  'sushi': ['fresco', 'arte', 'japonés', 'delicado', 'crudo'],
  'tacos': ['fiesta', 'mexicano', 'picante', 'relleno', 'crujiente'],
  'pancakes': ['desayuno', 'esponjoso', 'dulce', 'domingo', 'familia'],
  'chocolate': ['tentación', 'dulce', 'regalo', 'confort', 'derretido'],
  'sandía': ['verano', 'refrescante', 'semillas', 'rojo', 'jugoso'],
  'piña': ['tropical', 'ácido', 'espinoso', 'exótico', 'amarillo'],
  'aguacate': ['cremoso', 'saludable', 'verde', 'moderno', 'tostada'],
  'croissant': ['francés', 'hojaldrado', 'mantequilla', 'desayuno', 'café'],
  'burrito': ['enrollado', 'abundante', 'mexicano', 'relleno', 'grande'],
  'lasaña': ['capas', 'italiano', 'horno', 'familia', 'abundante'],
  'pastel': ['celebración', 'dulce', 'cumpleaños', 'decorado', 'soplar'],
  'pretzel': ['retorcido', 'salado', 'alemán', 'crujiente', 'festival'],
  'palomitas': ['cine', 'crujiente', 'salado', 'compartir', 'película'],
  'empanada': ['relleno', 'dorado', 'caliente', 'hogar', 'tradición'],
  'waffle': ['cuadros', 'desayuno', 'belga', 'dulce', 'crujiente'],
  'sándwich': ['rápido', 'práctico', 'capas', 'almuerzo', 'picnic'],
  'nachos': ['crujiente', 'compartir', 'mexicano', 'fiesta', 'derretido'],
  'paella': ['español', 'amarillo', 'familiar', 'domingo', 'festivo'],
  'ceviche': ['fresco', 'ácido', 'peruano', 'marino', 'picante'],
  'arepa': ['venezolano', 'relleno', 'redondo', 'caliente', 'maíz'],
  'churros': ['dulce', 'español', 'crujiente', 'feria', 'mojado'],
  'helado': ['frío', 'verano', 'cremoso', 'dulce', 'derretir'],
  'flan': ['suave', 'caramelo', 'temblor', 'postre', 'cremoso'],
  'ensalada': ['fresco', 'saludable', 'verde', 'crujiente', 'ligero'],
  'sopa': ['caliente', 'reconfortante', 'invierno', 'hogar', 'cuchara'],
  'arroz': ['básico', 'versátil', 'asiático', 'blanco', 'acompañante'],
  'pollo': ['versátil', 'familiar', 'domingo', 'económico', 'común'],

  // === PLACES ===
  'playa': ['relajante', 'verano', 'arena', 'vacaciones', 'horizonte'],
  'montaña': ['desafiante', 'aire fresco', 'altura', 'aventura', 'silencio'],
  'biblioteca': ['silencio', 'conocimiento', 'tranquilo', 'concentración', 'orden'],
  'hospital': ['esteril', 'preocupación', 'esperanza', 'urgente', 'cuidado'],
  'aeropuerto': ['espera', 'despedidas', 'madrugada', 'equipaje', 'nervios'],
  'museo': ['historia', 'silencio', 'admiración', 'cultura', 'antiguo'],
  'estadio': ['emoción', 'multitud', 'gritos', 'pasión', 'victoria'],
  'restaurante': ['celebración', 'servicio', 'espera', 'elegante', 'cita'],
  'casino': ['suerte', 'riesgo', 'luces', 'nocturno', 'tentación'],
  'zoológico': ['familar', 'educativo', 'encerrado', 'observar', 'fin de semana'],
  'parque': ['familia', 'paseo', 'verde', 'niños', 'descanso'],
  'cine': ['oscuro', 'palomitas', 'escapar', 'silencio', 'pantalla'],
  'teatro': ['dramático', 'elegante', 'aplausos', 'cultura', 'cortina'],
  'iglesia': ['silencio', 'paz', 'reflexión', 'domingo', 'comunidad'],
  'supermercado': ['lista', 'comparar', 'carritos', 'rutina', 'fila'],
  'escuela': ['aprendizaje', 'amigos', 'rutina', 'timbre', 'memorias'],
  'universidad': ['libertad', 'exámenes', 'futuro', 'independencia', 'estudio'],
  'gimnasio': ['esfuerzo', 'sudor', 'disciplina', 'espejo', 'rutina'],
  'piscina': ['refrescante', 'verano', 'cloro', 'zambullida', 'flotador'],
  'jardín': ['paz', 'colores', 'cuidado', 'primavera', 'aromas'],
  'plaza': ['encuentro', 'comunidad', 'descanso', 'palomas', 'centro'],
  'mercado': ['bullicio', 'colores', 'fresco', 'regatear', 'aromas'],
  'estación': ['espera', 'llegadas', 'despedidas', 'horarios', 'viajeros'],
  'puerto': ['olor a sal', 'comercio', 'gaviotas', 'horizonte', 'partidas'],
  'faro': ['guía', 'solitario', 'nocturno', 'alto', 'seguridad'],
  'castillo': ['medieval', 'misterioso', 'piedra', 'histórico', 'fantasía'],
  'palacio': ['lujo', 'grandioso', 'histórico', 'elegante', 'poder'],
  'pirámide': ['antiguo', 'misterioso', 'triangular', 'monumental', 'desierto'],
  'cueva': ['oscuro', 'frío', 'misterioso', 'eco', 'explorar'],
  'volcán': ['peligroso', 'poderoso', 'caliente', 'dormido', 'imponente'],

  // === PROFESSIONS ===
  'doctor': ['bata blanca', 'cuidado', 'confianza', 'estudio', 'vocación'],
  'bombero': ['valiente', 'emergencia', 'sirena', 'héroe', 'rojo'],
  'astronauta': ['aventura', 'entrenamiento', 'aislado', 'pionero', 'sueño'],
  'chef': ['creativo', 'presión', 'sabores', 'pasión', 'calor'],
  'piloto': ['responsabilidad', 'viajes', 'uniforme', 'altura', 'control'],
  'maestro': ['paciencia', 'vocación', 'influencia', 'pizarra', 'futuro'],
  'detective': ['observador', 'curioso', 'lógico', 'misterio', 'pistas'],
  'arquitecto': ['visión', 'creativo', 'planos', 'espacios', 'diseño'],
  'cirujano': ['precisión', 'presión', 'manos firmes', 'concentración', 'largo'],
  'músico': ['expresivo', 'práctica', 'emocional', 'talento', 'escenario'],
  'abogado': ['argumentos', 'formal', 'defensa', 'justicia', 'palabras'],
  'policía': ['protección', 'orden', 'uniforme', 'comunidad', 'patrulla'],
  'veterinario': ['compasivo', 'animales', 'cuidado', 'vocación', 'paciencia'],
  'periodista': ['curioso', 'rápido', 'veracidad', 'noticias', 'investigar'],
  'ingeniero': ['analítico', 'soluciones', 'lógico', 'construir', 'calcular'],
  'dentista': ['precisión', 'higiene', 'nervios', 'sonrisas', 'revisión'],
  'enfermero': ['cuidado', 'turno nocturno', 'compasión', 'agotador', 'dedicado'],
  'fotógrafo': ['observador', 'momento', 'luz', 'creatividad', 'perspectiva'],
  'pintor': ['creativo', 'colores', 'expresivo', 'solitario', 'inspiración'],
  'actor': ['versátil', 'emocional', 'memorizar', 'nervios', 'aplausos'],
  'cantante': ['emocional', 'escenario', 'ensayo', 'nervios', 'micrófono'],
  'bailarín': ['disciplina', 'gracia', 'físico', 'expresivo', 'ensayo'],
  'escritor': ['solitario', 'imaginativo', 'observador', 'disciplina', 'café'],
  'científico': ['curioso', 'metódico', 'paciente', 'descubrimiento', 'laboratorio'],
  'programador': ['lógico', 'nocturno', 'problema', 'café', 'creativo'],
  'mecánico': ['práctico', 'manchado', 'diagnóstico', 'herramientas', 'reparar'],
  'electricista': ['cuidadoso', 'técnico', 'cables', 'peligroso', 'reparar'],
  'carpintero': ['tradicional', 'madera', 'medidas', 'creativo', 'herramientas'],
  'panadero': ['madrugada', 'aroma', 'calor', 'tradicional', 'masa'],
  'jardinero': ['paciente', 'naturaleza', 'estaciones', 'cuidado', 'tranquilo'],

  // === MOVIES ===
  // Note: 'tiburón' (Jaws) uses same hints as the animal 'tiburón' (shark) defined above
  'titanic': ['trágico', 'romántico', 'frío', 'inolvidable', 'clásico'],
  'avatar': ['fantástico', 'azul', 'naturaleza', 'tecnología', 'otro mundo'],
  'frozen': ['frío', 'musical', 'hermanas', 'magia', 'liberación'],
  'batman': ['oscuro', 'nocturno', 'justicia', 'solitario', 'venganza'],
  'shrek': ['diferente', 'humor', 'amistad', 'pantano', 'capas'],
  'origen': ['confuso', 'sueños', 'laberinto', 'profundo', 'giro'],
  'gladiador': ['épico', 'venganza', 'arena', 'honor', 'antiguo'],
  'matrix': ['filosófico', 'realidad', 'elección', 'revolucionario', 'negro'],
  'coco': ['familia', 'música', 'tradición', 'colorido', 'recuerdos'],
  'up': ['aventura', 'emocional', 'sueños', 'globos', 'amistad'],
  'ratatouille': ['aspiraciones', 'cocina', 'pequeño', 'sueños', 'francia'],
  'toy story': ['infancia', 'amistad', 'nostalgia', 'lealtad', 'aventura'],
  'buscando a nemo': ['familia', 'océano', 'aventura', 'perseverancia', 'colorido'],
  'cars': ['velocidad', 'amistad', 'humildad', 'rural', 'carreras'],
  'moana': ['océano', 'aventura', 'identidad', 'valiente', 'musical'],
  'encanto': ['familia', 'magia', 'único', 'musical', 'colombiano'],
  'spider-man': ['responsabilidad', 'joven', 'ciudad', 'secreto', 'ágil'],
  'iron man': ['tecnología', 'genio', 'arrogante', 'transformación', 'metal'],
  'thor': ['mitología', 'poder', 'familia', 'héroe', 'nórdico'],
  'jurassic park': ['prehistórico', 'peligro', 'ciencia', 'aventura', 'isla'],
  'harry potter': ['magia', 'amistad', 'destino', 'misterio', 'escuela'],
  'star wars': ['épico', 'familia', 'destino', 'galaxia', 'clásico'],
  'el padrino': ['familia', 'poder', 'lealtad', 'oscuro', 'clásico'],
  'forrest gump': ['inocente', 'histórico', 'correr', 'destino', 'amor'],
  'rocky': ['esfuerzo', 'underdog', 'inspirador', 'entrenamiento', 'pelea'],
  'rambo': ['supervivencia', 'solitario', 'jungla', 'acción', 'trauma'],
  'terminator': ['futuro', 'imparable', 'metal', 'persecución', 'destino'],
  'alien': ['terror', 'aislado', 'oscuro', 'supervivencia', 'espacio'],
  'indiana jones': ['aventura', 'arqueología', 'peligro', 'sombrero', 'clásico'],

  // === SPORTS ===
  'fútbol': ['pasión', 'global', 'equipo', 'domingo', 'goles'],
  'baloncesto': ['alto', 'rápido', 'cancha', 'americano', 'saltos'],
  'tenis': ['elegante', 'individual', 'concentración', 'blanco', 'rally'],
  'natación': ['refrescante', 'respiración', 'disciplina', 'madrugada', 'piscina'],
  'béisbol': ['americano', 'lento', 'estadio', 'verano', 'familia'],
  'voleibol': ['playa', 'equipo', 'saltos', 'verano', 'red'],
  'golf': ['paciencia', 'silencio', 'verde', 'exclusivo', 'tranquilo'],
  'boxeo': ['intenso', 'disciplina', 'uno a uno', 'sudor', 'ring'],
  'ciclismo': ['resistencia', 'paisajes', 'libertad', 'velocidad', 'subidas'],
  'atletismo': ['básico', 'velocidad', 'pista', 'marcas', 'esfuerzo'],
  'surf': ['libertad', 'olas', 'equilibrio', 'verano', 'californiano'],
  'esquí': ['frío', 'velocidad', 'invierno', 'montaña', 'blanco'],
  'patinaje': ['gracia', 'equilibrio', 'hielo', 'elegante', 'giros'],
  'karate': ['disciplina', 'respeto', 'oriental', 'cinturón', 'control'],
  'judo': ['caídas', 'respeto', 'agarre', 'oriental', 'tatami'],
  'hockey': ['frío', 'rápido', 'equipo', 'canadiense', 'intenso'],
  'rugby': ['físico', 'equipo', 'barro', 'respeto', 'oval'],
  'cricket': ['inglés', 'lento', 'tradición', 'elegante', 'verano'],
  'bádminton': ['rápido', 'pluma', 'ligero', 'asiático', 'reflejos'],
  'ping pong': ['rápido', 'reflejos', 'pequeño', 'asiático', 'interior'],
  'escalada': ['vertical', 'fuerza', 'mental', 'aventura', 'agarres'],
  'paracaidismo': ['adrenalina', 'caída', 'libertad', 'valentía', 'cielo'],
  'buceo': ['silencio', 'profundo', 'respiración', 'colores', 'paz'],
  'vela': ['viento', 'libertad', 'paciencia', 'horizonte', 'silencioso'],
  'remo': ['ritmo', 'equipo', 'madrugada', 'agua', 'sincronizado'],
  'gimnasia': ['flexibilidad', 'gracia', 'perfección', 'disciplina', 'joven'],
  'lucha': ['antiguo', 'fuerza', 'tradición', 'contacto', 'olímpico'],
  'esgrima': ['elegante', 'estrategia', 'rápido', 'tradición', 'blanco'],
  'polo': ['exclusivo', 'velocidad', 'elegante', 'verde', 'tradición'],
  'equitación': ['elegante', 'conexión', 'disciplina', 'tradición', 'campo'],

  // === OBJECTS ===
  'teléfono': ['adictivo', 'comunicación', 'constante', 'personal', 'distracción'],
  'computadora': ['trabajo', 'conexión', 'información', 'moderno', 'pantalla'],
  'televisión': ['entretenimiento', 'pasivo', 'familiar', 'noticias', 'sofá'],
  'reloj': ['rutina', 'puntual', 'ansiedad', 'regalo', 'elegante'],
  'lámpara': ['ambiente', 'nocturno', 'lectura', 'decorativo', 'cálido'],
  'silla': ['descanso', 'común', 'oficina', 'esperar', 'reunión'],
  'mesa': ['encuentro', 'familia', 'trabajo', 'comer', 'central'],
  'cama': ['descanso', 'sueños', 'confort', 'íntimo', 'suave'],
  'espejo': ['reflexión', 'vanidad', 'verdad', 'mañana', 'decorativo'],
  'ventana': ['luz', 'exterior', 'aire', 'observar', 'escape'],
  'puerta': ['oportunidad', 'privacidad', 'entrada', 'cerrar', 'seguridad'],
  'escalera': ['esfuerzo', 'subir', 'etapas', 'edificio', 'ejercicio'],
  'ascensor': ['esperar', 'pequeño', 'rápido', 'incómodo', 'moderno'],
  'bicicleta': ['libertad', 'ejercicio', 'ecológico', 'infancia', 'equilibrio'],
  'carro': ['independencia', 'viajes', 'tráfico', 'libertad', 'caro'],
  'avión': ['distancia', 'rápido', 'nervios', 'altura', 'ventanilla'],
  'barco': ['lento', 'horizonte', 'mareo', 'vacaciones', 'romantico'],
  'tren': ['viaje', 'paisajes', 'puntual', 'nostálgico', 'ritmo'],
  'moto': ['libertad', 'adrenalina', 'joven', 'rápido', 'viento'],
  'patineta': ['joven', 'urbano', 'trucos', 'rebelde', 'equilibrio'],
  'guitarra': ['romántico', 'fogata', 'expresivo', 'aprender', 'acústico'],
  'piano': ['elegante', 'clásico', 'dedicación', 'grande', 'expresivo'],
  'tambor': ['ritmo', 'primitivo', 'fiesta', 'energía', 'tribal'],
  'violín': ['emocional', 'clásico', 'difícil', 'orquesta', 'elegante'],
  'flauta': ['dulce', 'antiguo', 'escuela', 'aire', 'melodía'],
  'cámara': ['memorias', 'momento', 'viajes', 'observar', 'capturar'],
  'libro': ['escape', 'conocimiento', 'imaginación', 'tranquilo', 'viejo'],
  'lápiz': ['ideas', 'escuela', 'borrar', 'simple', 'creativo'],
  'tijeras': ['cortar', 'preciso', 'manualidades', 'peligroso', 'escolar'],
  'paraguas': ['protección', 'lluvia', 'olvidado', 'ciudad', 'gris'],

  // === NATURE ===
  'árbol': ['sombra', 'antiguo', 'crecimiento', 'raíces', 'hogar'],
  'flor': ['regalo', 'efímero', 'aroma', 'primavera', 'romántico'],
  'río': ['fluir', 'constante', 'frontera', 'vida', 'viaje'],
  'lago': ['tranquilo', 'reflejo', 'profundo', 'misterioso', 'silencio'],
  'océano': ['inmenso', 'misterioso', 'poderoso', 'horizonte', 'profundo'],
  'bosque': ['paz', 'misterioso', 'verde', 'refugio', 'antiguo'],
  'selva': ['denso', 'húmedo', 'salvaje', 'ruidos', 'peligroso'],
  'desierto': ['vacío', 'calor', 'soledad', 'extremo', 'dorado'],
  'isla': ['aislado', 'escape', 'tropical', 'pequeño', 'paraíso'],
  'cascada': ['poderoso', 'ruido', 'fresco', 'majestuoso', 'aventura'],
  'arcoíris': ['esperanza', 'efímero', 'magia', 'después de lluvia', 'colores'],
  'nube': ['suave', 'formas', 'blanco', 'cambio', 'soñar'],
  'sol': ['energía', 'calor', 'despertar', 'vida', 'brillante'],
  'luna': ['nocturno', 'romántico', 'ciclos', 'misterioso', 'plateado'],
  'estrella': ['deseo', 'lejano', 'nocturno', 'brillante', 'navegación'],
  'lluvia': ['melancolía', 'limpieza', 'sonido', 'gris', 'refrescante'],
  'nieve': ['silencio', 'frío', 'blanco', 'navidad', 'puro'],
  'trueno': ['miedo', 'poderoso', 'advertencia', 'ruido', 'tormenta'],
  'relámpago': ['rápido', 'peligroso', 'brillante', 'energía', 'fugaz'],
  'tornado': ['destructivo', 'giratorio', 'miedo', 'poderoso', 'caótico'],
  'terremoto': ['miedo', 'destructivo', 'impredecible', 'temblar', 'pánico'],
  'maremoto': ['destructivo', 'gigante', 'pánico', 'costero', 'rápido'],
  'glaciar': ['antiguo', 'frío', 'lento', 'azul', 'derritiendo'],
  'aurora': ['mágico', 'nocturno', 'norte', 'colorido', 'efímero'],
  'amanecer': ['nuevo', 'esperanza', 'temprano', 'naranja', 'comienzo'],
  'atardecer': ['romántico', 'naranja', 'tranquilo', 'fin', 'contemplar'],
  'coral': ['colorido', 'frágil', 'submarino', 'colonia', 'protegido'],
  'alga': ['verde', 'resbaladizo', 'marino', 'comida', 'enredo'],
  'hongo': ['oscuro', 'húmedo', 'misterioso', 'bosque', 'rápido'],
  'cactus': ['resistente', 'espinas', 'seco', 'verde', 'solitario']
};
