import { WordHintsMap } from '../types';

/**
 * Dutch hints for imposter - Following Three-Filter Rule:
 * 1. Related but not defining
 * 2. Specific in intent but vague in interpretation
 * 3. Never directly reveal the secret word
 *
 * Hints are experiences, emotions, or abstract concepts - NOT synonyms,
 * translations, direct categories, or physical components.
 */
export const nlWordHints: WordHintsMap = {
  // === ANIMALS (Dieren) ===
  'olifant': ['zwaar', 'wijs', 'grijs', 'geheugen', 'majestueus'],
  'giraffe': ['lang', 'gevlekt', 'elegant', 'rustig', 'nieuwsgierig'],
  'pinguïn': ['koud', 'elegant', 'onhandig', 'familie', 'smoking'],
  'dolfijn': ['intelligent', 'speels', 'sprongen', 'vriendelijk', 'marien'],
  'kangoeroe': ['springen', 'buidel', 'australië', 'gespierd', 'beschermend'],
  'octopus': ['flexibel', 'intelligent', 'mysterieus', 'verborgen', 'diep'],
  'vlinder': ['transformatie', 'delicaat', 'kleurrijk', 'vluchtig', 'vrij'],
  'krokodil': ['geduldig', 'oud', 'gevaarlijk', 'stil', 'hinderlaag'],
  'flamingo': ['roze', 'elegant', 'evenwicht', 'tropisch', 'groep'],
  'egel': ['defensief', 'klein', 'nachtelijk', 'verlegen', 'bal'],
  'koala': ['slaperig', 'knuffel', 'langzaam', 'australië', 'omarmen'],
  'luipaard': ['gevlekt', 'sluipend', 'snel', 'eenzaam', 'nachtelijk'],
  'panda': ['schattig', 'rustig', 'bamboe', 'zeldzaam', 'zachtaardig'],
  'wasbeer': ['ondeugende', 'nachtelijk', 'nieuwsgierig', 'masker', 'slim'],
  'zebra': ['strepen', 'kudde', 'snel', 'afrikaans', 'uniek'],
  'gorilla': ['sterk', 'familie', 'intelligent', 'beschermend', 'imposant'],
  'jachtluipaard': ['snelheid', 'gevlekt', 'afrikaans', 'elegant', 'eenzaam'],
  'pauw': ['pronken', 'kleurrijk', 'vertoning', 'trots', 'tuin'],
  'nijlpaard': ['zwaar', 'water', 'territoriaal', 'gevaarlijk', 'groot'],
  'gordeldier': ['gepantserd', 'graver', 'nachtelijk', 'verlegen', 'bal'],
  'adelaar': ['vrij', 'scherp zicht', 'majestueus', 'hoogte', 'krachtig'],
  'haai': ['gevreesd', 'oud', 'eenzaam', 'jager', 'diep'],
  'schildpad': ['langzaam', 'lang leven', 'geduldig', 'beschermd', 'wijs'],
  'kameleon': ['verandering', 'aanpasbaar', 'geduldig', 'waarnemer', 'uniek'],
  'wolf': ['roedel', 'huilen', 'loyaal', 'nachtelijk', 'wild'],
  'beer': ['winterslaap', 'sterk', 'eenzaam', 'beschermend', 'bos'],
  'leeuw': ['trots', 'leider', 'majestueus', 'familie', 'savanne'],
  'tijger': ['strepen', 'eenzaam', 'krachtig', 'sluipend', 'oranje'],
  'slang': ['stil', 'flexibel', 'koud', 'hypnotisch', 'vervellen'],
  'uil': ['nachtelijk', 'wijs', 'stil', 'draaien', 'waarnemer'],

  // === FOOD (Eten) ===
  'pizza': ['delen', 'feest', 'rond', 'heet', 'favoriet'],
  'hamburger': ['snel', 'sappig', 'amerikaans', 'bevredigend', 'lagen'],
  'spaghetti': ['draaien', 'italiaans', 'lang', 'romantisch', 'traditioneel'],
  'sushi': ['vers', 'kunst', 'japans', 'delicaat', 'rauw'],
  'taco': ['feest', 'mexicaans', 'pittig', 'gevuld', 'knapperig'],
  'pannenkoeken': ['ontbijt', 'luchtig', 'zoet', 'zondag', 'familie'],
  'chocolade': ['verleiding', 'zoet', 'cadeau', 'troost', 'gesmolten'],
  'watermeloen': ['zomer', 'verfrissend', 'pitten', 'rood', 'sappig'],
  'ananas': ['tropisch', 'zuur', 'stekelig', 'exotisch', 'geel'],
  'avocado': ['romig', 'gezond', 'groen', 'trendy', 'toast'],
  'croissant': ['frans', 'bladerdeeg', 'boter', 'ontbijt', 'koffie'],
  'burrito': ['gerold', 'vulling', 'mexicaans', 'gevuld', 'groot'],
  'lasagne': ['lagen', 'italiaans', 'oven', 'familie', 'stevig'],
  'taart': ['viering', 'zoet', 'verjaardag', 'versierd', 'kaarsjes'],
  'pretzel': ['gedraaid', 'zout', 'duits', 'knapperig', 'festival'],
  'popcorn': ['bioscoop', 'knapperig', 'zout', 'delen', 'film'],
  'empanada': ['gevuld', 'goudbruin', 'warm', 'huisgemaakt', 'traditie'],
  'wafel': ['vakjes', 'ontbijt', 'belgisch', 'zoet', 'knapperig'],
  'boterham': ['snel', 'praktisch', 'lagen', 'lunch', 'picknick'],
  'nachos': ['knapperig', 'delen', 'mexicaans', 'feest', 'gesmolten'],
  'paella': ['spaans', 'geel', 'familie', 'zondag', 'feestelijk'],
  'stroopwafel': ['zoet', 'plakkerig', 'koffie', 'hollands', 'warm'],
  'bitterballen': ['feest', 'warm', 'borrel', 'hollands', 'knapperig'],
  'poffertjes': ['klein', 'zoet', 'poeder', 'markt', 'traditie'],
  'ijs': ['koud', 'zomer', 'romig', 'zoet', 'smelt'],
  'pudding': ['zacht', 'karamel', 'wiebelen', 'dessert', 'romig'],
  'salade': ['vers', 'gezond', 'groen', 'knapperig', 'licht'],
  'soep': ['warm', 'troostend', 'winter', 'huisgemaakt', 'lepel'],
  'rijst': ['basis', 'veelzijdig', 'aziatisch', 'wit', 'bijgerecht'],
  'kip': ['veelzijdig', 'familie', 'zondag', 'betaalbaar', 'gewoon'],

  // === PLACES (Plaatsen) ===
  'strand': ['ontspannend', 'zomer', 'zand', 'vakantie', 'horizon'],
  'berg': ['uitdagend', 'frisse lucht', 'hoogte', 'avontuur', 'stilte'],
  'bibliotheek': ['stilte', 'kennis', 'rustig', 'concentratie', 'orde'],
  'ziekenhuis': ['steriel', 'zorgen', 'hoop', 'urgent', 'zorg'],
  'vliegveld': ['wachten', 'afscheid', 'vroeg', 'bagage', 'zenuwen'],
  'museum': ['geschiedenis', 'stilte', 'bewondering', 'cultuur', 'oud'],
  'stadion': ['spanning', 'menigte', 'juichen', 'passie', 'overwinning'],
  'restaurant': ['viering', 'bediening', 'wachten', 'elegant', 'afspraakje'],
  'casino': ['geluk', 'risico', 'lichten', 'nachtelijk', 'verleiding'],
  'dierentuin': ['familie', 'leerzaam', 'opgesloten', 'kijken', 'weekend'],
  'park': ['familie', 'wandeling', 'groen', 'kinderen', 'rust'],
  'bioscoop': ['donker', 'popcorn', 'ontsnappen', 'stilte', 'scherm'],
  'theater': ['dramatisch', 'elegant', 'applaus', 'cultuur', 'gordijn'],
  'kerk': ['stilte', 'vrede', 'bezinning', 'zondag', 'gemeenschap'],
  'supermarkt': ['lijstje', 'vergelijken', 'karretjes', 'routine', 'rij'],
  'school': ['leren', 'vrienden', 'routine', 'bel', 'herinneringen'],
  'universiteit': ['vrijheid', 'examens', 'toekomst', 'onafhankelijk', 'studeren'],
  'sportschool': ['inspanning', 'zweet', 'discipline', 'spiegels', 'routine'],
  'zwembad': ['verfrissend', 'zomer', 'chloor', 'duiken', 'drijven'],
  'tuin': ['vrede', 'kleuren', 'verzorging', 'lente', 'geuren'],
  'plein': ['ontmoeting', 'gemeenschap', 'rusten', 'duiven', 'centrum'],
  'markt': ['drukte', 'kleuren', 'vers', 'onderhandelen', 'geuren'],
  'station': ['wachten', 'aankomst', 'afscheid', 'roosters', 'reizigers'],
  'haven': ['zoute lucht', 'handel', 'meeuwen', 'horizon', 'vertrek'],
  'vuurtoren': ['gids', 'eenzaam', 'nachtelijk', 'hoog', 'veiligheid'],
  'kasteel': ['middeleeuws', 'mysterieus', 'steen', 'historisch', 'fantasie'],
  'paleis': ['luxe', 'groots', 'historisch', 'elegant', 'macht'],
  'piramide': ['oud', 'mysterieus', 'driehoekig', 'monumentaal', 'woestijn'],
  'grot': ['donker', 'koud', 'mysterieus', 'echo', 'ontdekken'],
  'vulkaan': ['gevaarlijk', 'krachtig', 'heet', 'slapend', 'imposant'],

  // === PROFESSIONS (Beroepen) ===
  'dokter': ['witte jas', 'zorgzaam', 'vertrouwen', 'studeren', 'roeping'],
  'brandweerman': ['dapper', 'noodgeval', 'sirene', 'held', 'rood'],
  'astronaut': ['avontuur', 'training', 'geïsoleerd', 'pionier', 'droom'],
  'kok': ['creatief', 'druk', 'smaken', 'passie', 'hitte'],
  'piloot': ['verantwoordelijkheid', 'reizen', 'uniform', 'hoogte', 'controle'],
  'leraar': ['geduld', 'roeping', 'invloed', 'bord', 'toekomst'],
  'detective': ['oplettend', 'nieuwsgierig', 'logisch', 'mysterie', 'aanwijzingen'],
  'architect': ['visie', 'creatief', 'tekeningen', 'ruimtes', 'ontwerp'],
  'chirurg': ['precisie', 'druk', 'vaste handen', 'concentratie', 'lang'],
  'muzikant': ['expressief', 'oefenen', 'emotioneel', 'talent', 'podium'],
  'advocaat': ['argumenten', 'formeel', 'verdediging', 'rechtvaardigheid', 'woorden'],
  'politieagent': ['bescherming', 'orde', 'uniform', 'gemeenschap', 'patrouille'],
  'dierenarts': ['mededogen', 'dieren', 'zorgzaam', 'roeping', 'geduld'],
  'journalist': ['nieuwsgierig', 'snel', 'waarheid', 'nieuws', 'onderzoeken'],
  'ingenieur': ['analytisch', 'oplossingen', 'logisch', 'bouwen', 'berekenen'],
  'tandarts': ['precisie', 'hygiëne', 'zenuwen', 'glimlachen', 'controle'],
  'verpleegster': ['zorgzaam', 'nachtdienst', 'mededogen', 'uitputtend', 'toegewijd'],
  'fotograaf': ['oplettend', 'moment', 'licht', 'creativiteit', 'perspectief'],
  'schilder': ['creatief', 'kleuren', 'expressief', 'eenzaam', 'inspiratie'],
  'acteur': ['veelzijdig', 'emotioneel', 'onthouden', 'zenuwen', 'applaus'],
  'zanger': ['emotioneel', 'podium', 'repetitie', 'zenuwen', 'microfoon'],
  'danser': ['discipline', 'gratie', 'fysiek', 'expressief', 'repetitie'],
  'schrijver': ['eenzaam', 'fantasierijk', 'oplettend', 'discipline', 'koffie'],
  'wetenschapper': ['nieuwsgierig', 'methodisch', 'geduldig', 'ontdekking', 'laboratorium'],
  'programmeur': ['logisch', 'nachtelijk', 'probleem', 'koffie', 'creatief'],
  'monteur': ['praktisch', 'vuil', 'diagnose', 'gereedschap', 'repareren'],
  'elektricien': ['voorzichtig', 'technisch', 'draden', 'gevaarlijk', 'repareren'],
  'timmerman': ['traditioneel', 'hout', 'meten', 'creatief', 'gereedschap'],
  'bakker': ['vroeg opstaan', 'geur', 'warmte', 'traditioneel', 'deeg'],
  'tuinman': ['geduldig', 'natuur', 'seizoenen', 'verzorging', 'rustig'],

  // === MOVIES (Films) ===
  'titanic': ['tragisch', 'romantisch', 'koud', 'onvergetelijk', 'klassiek'],
  'avatar': ['fantastisch', 'blauw', 'natuur', 'technologie', 'andere wereld'],
  'frozen': ['koud', 'musical', 'zussen', 'magie', 'bevrijding'],
  'jaws': ['angst', 'zomer', 'water', 'spanning', 'klassiek'],
  'batman': ['donker', 'nachtelijk', 'gerechtigheid', 'eenzaam', 'wraak'],
  'shrek': ['anders', 'humor', 'vriendschap', 'moeras', 'lagen'],
  'inception': ['verwarrend', 'dromen', 'labyrint', 'diep', 'plot twist'],
  'gladiator': ['episch', 'wraak', 'arena', 'eer', 'oud'],
  'matrix': ['filosofisch', 'werkelijkheid', 'keuze', 'revolutionair', 'zwart'],
  'coco': ['familie', 'muziek', 'traditie', 'kleurrijk', 'herinneringen'],
  'up': ['avontuur', 'emotioneel', 'dromen', 'ballonnen', 'vriendschap'],
  'ratatouille': ['ambities', 'koken', 'klein', 'dromen', 'frankrijk'],
  'toy story': ['kindertijd', 'vriendschap', 'nostalgie', 'loyaliteit', 'avontuur'],
  'finding nemo': ['familie', 'oceaan', 'avontuur', 'doorzettingsvermogen', 'kleurrijk'],
  'cars': ['snelheid', 'vriendschap', 'bescheidenheid', 'landelijk', 'racen'],
  'moana': ['oceaan', 'avontuur', 'identiteit', 'dapper', 'musical'],
  'encanto': ['familie', 'magie', 'uniek', 'musical', 'colombiaans'],
  'spider-man': ['verantwoordelijkheid', 'jong', 'stad', 'geheim', 'behendig'],
  'iron man': ['technologie', 'genie', 'arrogant', 'transformatie', 'metaal'],
  'thor': ['mythologie', 'kracht', 'familie', 'held', 'noors'],
  'jurassic park': ['prehistorisch', 'gevaar', 'wetenschap', 'avontuur', 'eiland'],
  'harry potter': ['magie', 'vriendschap', 'lot', 'mysterie', 'school'],
  'star wars': ['episch', 'familie', 'lot', 'melkweg', 'klassiek'],
  'the godfather': ['familie', 'macht', 'loyaliteit', 'donker', 'klassiek'],
  'forrest gump': ['onschuldig', 'historisch', 'rennen', 'lot', 'liefde'],
  'rocky': ['inspanning', 'underdog', 'inspirerend', 'training', 'vechten'],
  'rambo': ['overleven', 'eenling', 'jungle', 'actie', 'trauma'],
  'terminator': ['toekomst', 'onstopbaar', 'metaal', 'achtervolging', 'lot'],
  'alien': ['horror', 'geïsoleerd', 'donker', 'overleven', 'ruimte'],
  'indiana jones': ['avontuur', 'archeologie', 'gevaar', 'hoed', 'klassiek'],

  // === SPORTS (Sport) ===
  'voetbal': ['passie', 'wereldwijd', 'team', 'zondag', 'doelpunten'],
  'basketbal': ['lang', 'snel', 'veld', 'amerikaans', 'springen'],
  'tennis': ['elegant', 'individueel', 'concentratie', 'wit', 'rally'],
  'zwemmen': ['verfrissend', 'ademhaling', 'discipline', 'vroeg', 'zwembad'],
  'honkbal': ['amerikaans', 'langzaam', 'stadion', 'zomer', 'familie'],
  'volleybal': ['strand', 'team', 'springen', 'zomer', 'net'],
  'golf': ['geduld', 'stilte', 'groen', 'exclusief', 'rustig'],
  'boksen': ['intens', 'discipline', 'één tegen één', 'zweet', 'ring'],
  'fietsen': ['uithoudingsvermogen', 'landschap', 'vrijheid', 'snelheid', 'heuvels'],
  'atletiek': ['basis', 'snelheid', 'baan', 'records', 'inspanning'],
  'surfen': ['vrijheid', 'golven', 'balans', 'zomer', 'californisch'],
  'skiën': ['koud', 'snelheid', 'winter', 'berg', 'wit'],
  'schaatsen': ['gratie', 'balans', 'ijs', 'elegant', 'pirouettes'],
  'karate': ['discipline', 'respect', 'oosters', 'band', 'controle'],
  'judo': ['worpen', 'respect', 'greep', 'oosters', 'mat'],
  'hockey': ['koud', 'snel', 'team', 'canadees', 'intens'],
  'rugby': ['fysiek', 'team', 'modder', 'respect', 'ovaal'],
  'cricket': ['engels', 'langzaam', 'traditie', 'elegant', 'zomer'],
  'badminton': ['snel', 'veer', 'licht', 'aziatisch', 'reflexen'],
  'tafeltennis': ['snel', 'reflexen', 'klein', 'aziatisch', 'binnen'],
  'klimmen': ['verticaal', 'kracht', 'mentaal', 'avontuur', 'grepen'],
  'parachutespringen': ['adrenaline', 'vallen', 'vrijheid', 'moed', 'lucht'],
  'duiken': ['stilte', 'diep', 'ademhaling', 'kleuren', 'rust'],
  'zeilen': ['wind', 'vrijheid', 'geduld', 'horizon', 'stil'],
  'roeien': ['ritme', 'team', 'vroeg', 'water', 'synchroon'],
  'gymnastiek': ['flexibiliteit', 'gratie', 'perfectie', 'discipline', 'jong'],
  'worstelen': ['oud', 'kracht', 'traditie', 'contact', 'olympisch'],
  'schermen': ['elegant', 'strategie', 'snel', 'traditie', 'wit'],
  'polo': ['exclusief', 'snelheid', 'elegant', 'groen', 'traditie'],
  'paardrijden': ['elegant', 'verbinding', 'discipline', 'traditie', 'platteland'],

  // === OBJECTS (Voorwerpen) ===
  'telefoon': ['verslavend', 'communicatie', 'constant', 'persoonlijk', 'afleiding'],
  'computer': ['werk', 'verbinding', 'informatie', 'modern', 'scherm'],
  'televisie': ['entertainment', 'passief', 'familie', 'nieuws', 'bank'],
  'klok': ['routine', 'punctueel', 'spanning', 'cadeau', 'elegant'],
  'lamp': ['sfeer', 'nachtelijk', 'lezen', 'decoratief', 'warm'],
  'stoel': ['rust', 'gewoon', 'kantoor', 'wachten', 'vergadering'],
  'tafel': ['samen', 'familie', 'werk', 'eten', 'centraal'],
  'bed': ['rust', 'dromen', 'comfort', 'intiem', 'zacht'],
  'spiegel': ['reflectie', 'ijdelheid', 'waarheid', 'ochtend', 'decoratief'],
  'raam': ['licht', 'buiten', 'lucht', 'kijken', 'ontsnappen'],
  'deur': ['kans', 'privacy', 'ingang', 'sluiten', 'veiligheid'],
  'trap': ['inspanning', 'omhoog', 'etappes', 'gebouw', 'beweging'],
  'lift': ['wachten', 'klein', 'snel', 'ongemakkelijk', 'modern'],
  'fiets': ['vrijheid', 'beweging', 'ecologisch', 'kindertijd', 'balans'],
  'auto': ['onafhankelijkheid', 'reizen', 'verkeer', 'vrijheid', 'duur'],
  'vliegtuig': ['afstand', 'snel', 'zenuwen', 'hoogte', 'raampje'],
  'boot': ['langzaam', 'horizon', 'zeeziek', 'vakantie', 'romantisch'],
  'trein': ['reis', 'landschap', 'punctueel', 'nostalgisch', 'ritme'],
  'motor': ['vrijheid', 'adrenaline', 'jong', 'snel', 'wind'],
  'skateboard': ['jong', 'stedelijk', 'trucs', 'rebels', 'balans'],
  'gitaar': ['romantisch', 'kampvuur', 'expressief', 'leren', 'akoestisch'],
  'piano': ['elegant', 'klassiek', 'toewijding', 'groot', 'expressief'],
  'drumstel': ['ritme', 'primitief', 'feest', 'energie', 'tribaal'],
  'viool': ['emotioneel', 'klassiek', 'moeilijk', 'orkest', 'elegant'],
  'fluit': ['zoet', 'oud', 'school', 'adem', 'melodie'],
  'camera': ['herinneringen', 'moment', 'reizen', 'observeren', 'vastleggen'],
  'boek': ['ontsnappen', 'kennis', 'fantasie', 'rustig', 'oud'],
  'potlood': ['ideeën', 'school', 'uitgummen', 'eenvoudig', 'creatief'],
  'schaar': ['knippen', 'precies', 'knutselen', 'gevaarlijk', 'school'],
  'paraplu': ['bescherming', 'regen', 'vergeten', 'stad', 'grijs'],

  // === NATURE (Natuur) ===
  'boom': ['schaduw', 'oud', 'groei', 'wortels', 'thuis'],
  'bloem': ['cadeau', 'vluchtig', 'geur', 'lente', 'romantisch'],
  'rivier': ['stromen', 'constant', 'grens', 'leven', 'reis'],
  'meer': ['rustig', 'reflectie', 'diep', 'mysterieus', 'stilte'],
  'oceaan': ['uitgestrekt', 'mysterieus', 'krachtig', 'horizon', 'diep'],
  'bos': ['vrede', 'mysterieus', 'groen', 'toevlucht', 'oud'],
  'jungle': ['dicht', 'vochtig', 'wild', 'geluiden', 'gevaarlijk'],
  'woestijn': ['leeg', 'hitte', 'eenzaamheid', 'extreem', 'goud'],
  'eiland': ['geïsoleerd', 'ontsnappen', 'tropisch', 'klein', 'paradijs'],
  'waterval': ['krachtig', 'lawaai', 'fris', 'majestueus', 'avontuur'],
  'regenboog': ['hoop', 'vluchtig', 'magisch', 'na de regen', 'kleuren'],
  'wolk': ['zacht', 'vormen', 'wit', 'veranderend', 'dromen'],
  'zon': ['energie', 'warmte', 'wakker', 'leven', 'helder'],
  'maan': ['nachtelijk', 'romantisch', 'cycli', 'mysterieus', 'zilver'],
  'ster': ['wens', 'ver', 'nachtelijk', 'helder', 'navigatie'],
  'regen': ['melancholie', 'reiniging', 'geluid', 'grijs', 'verfrissend'],
  'sneeuw': ['stilte', 'koud', 'wit', 'kerst', 'puur'],
  'donder': ['angst', 'krachtig', 'waarschuwing', 'lawaai', 'storm'],
  'bliksem': ['snel', 'gevaarlijk', 'helder', 'energie', 'vluchtig'],
  'tornado': ['verwoestend', 'draaiend', 'angst', 'krachtig', 'chaotisch'],
  'aardbeving': ['angst', 'verwoestend', 'onvoorspelbaar', 'schudden', 'paniek'],
  'tsunami': ['verwoestend', 'gigantisch', 'paniek', 'kust', 'snel'],
  'gletsjer': ['oud', 'koud', 'langzaam', 'blauw', 'smelten'],
  'noorderlicht': ['magisch', 'nachtelijk', 'noord', 'kleurrijk', 'vluchtig'],
  'zonsopgang': ['nieuw', 'hoop', 'vroeg', 'oranje', 'begin'],
  'zonsondergang': ['romantisch', 'oranje', 'vredig', 'einde', 'kijken'],
  'koraal': ['kleurrijk', 'fragiel', 'onderwater', 'kolonie', 'beschermd'],
  'zeewier': ['groen', 'glad', 'marien', 'voedsel', 'verward'],
  'paddenstoel': ['donker', 'vochtig', 'mysterieus', 'bos', 'snel'],
  'cactus': ['veerkrachtig', 'stekelig', 'droog', 'groen', 'eenzaam']
};
