import { WordHintsMap } from '../types';

/**
 * Dutch hints for imposter - Following Three-Filter Rule:
 * 1. Related but not defining
 * 2. Specific in intent but vague in interpretation
 * 3. Never directly reveal the secret word
 *
 * Hints are experiences, emotions, or abstract concepts - NOT synonyms,
 * translations, direct categories, or physical components.
 *
 * 400 words × 10 hints = 4000 hints total
 */
export const nlWordHints: WordHintsMap = {
  // === ANIMALS (Dieren - 50 words) ===
  'olifant': ['zwaar', 'wijs', 'grijs', 'geheugen', 'majestueus', 'zachtaardig', 'gerimpeld', 'parade', 'slurf', 'enorm'],
  'giraffe': ['lang', 'gevlekt', 'elegant', 'rustig', 'nieuwsgierig', 'sierlijk', 'zachtaardig', 'strekken', 'savanne', 'vredig'],
  'pinguïn': ['koud', 'elegant', 'onhandig', 'familie', 'smoking', 'waggelen', 'kolonie', 'trouw', 'duiken', 'arctisch'],
  'dolfijn': ['intelligent', 'speels', 'sprongen', 'vriendelijk', 'marien', 'klikken', 'lachend', 'acrobatisch', 'groep', 'therapeutisch'],
  'kangoeroe': ['springen', 'buidel', 'australië', 'gespierd', 'beschermend', 'boksen', 'veerkrachtig', 'outback', 'huppelen', 'moederlijk'],
  'octopus': ['flexibel', 'intelligent', 'mysterieus', 'verborgen', 'diep', 'camouflage', 'ontsnappen', 'inkt', 'slim', 'tentakels'],
  'vlinder': ['transformatie', 'delicaat', 'kleurrijk', 'vluchtig', 'vrij', 'sierlijk', 'tuin', 'metamorfose', 'zweven', 'lente'],
  'krokodil': ['geduldig', 'oud', 'gevaarlijk', 'stil', 'hinderlaag', 'tranen', 'loerend', 'prehistorisch', 'gepantserd', 'moeras'],
  'flamingo': ['roze', 'elegant', 'evenwicht', 'tropisch', 'groep', 'sierlijk', 'exotisch', 'wadend', 'opvallend', 'kleurrijk'],
  'egel': ['defensief', 'klein', 'nachtelijk', 'verlegen', 'bal', 'stekelig', 'schattig', 'tuin', 'opgerold', 'snuffelend'],
  'koala': ['slaperig', 'knuffel', 'langzaam', 'australië', 'omarmen', 'eucalyptus', 'vredig', 'pluizig', 'klimmend', 'lui'],
  'luipaard': ['gevlekt', 'sluipend', 'snel', 'eenzaam', 'nachtelijk', 'elegant', 'krachtig', 'stil', 'sierlijk', 'jager'],
  'panda': ['schattig', 'rustig', 'bamboe', 'zeldzaam', 'zachtaardig', 'vredig', 'zwart-wit', 'rollend', 'bedreigd', 'speels'],
  'wasbeer': ['ondeugende', 'nachtelijk', 'nieuwsgierig', 'masker', 'slim', 'vindingrijk', 'afval', 'bandiet', 'behendig', 'stedelijk'],
  'zebra': ['strepen', 'kudde', 'snel', 'afrikaans', 'uniek', 'patroon', 'stoffig', 'galopperen', 'wild', 'onderscheidend'],
  'gorilla': ['sterk', 'familie', 'intelligent', 'beschermend', 'imposant', 'borst', 'zachtaardig', 'zilverrug', 'krachtig', 'leider'],
  'jachtluipaard': ['snelheid', 'gevlekt', 'afrikaans', 'elegant', 'eenzaam', 'snelst', 'slank', 'sprint', 'sierlijk', 'jagend'],
  'pauw': ['pronken', 'kleurrijk', 'vertoning', 'trots', 'tuin', 'exotisch', 'paradend', 'iriseren', 'mooi', 'ijdel'],
  'nijlpaard': ['zwaar', 'water', 'territoriaal', 'gevaarlijk', 'groot', 'gapend', 'modderig', 'agressief', 'rivier', 'massief'],
  'gordeldier': ['gepantserd', 'graver', 'nachtelijk', 'verlegen', 'bal', 'prehistorisch', 'gravend', 'beplaat', 'rollend', 'woestijn'],
  'adelaar': ['vrij', 'scherp zicht', 'majestueus', 'hoogte', 'krachtig', 'zwevend', 'trots', 'symbool', 'jagend', 'woest'],
  'haai': ['gevreesd', 'oud', 'eenzaam', 'jager', 'diep', 'vin', 'cirkelend', 'krachtig', 'roofdier', 'stil'],
  'schildpad': ['langzaam', 'lang leven', 'geduldig', 'beschermd', 'wijs', 'oud', 'gestaag', 'schild', 'kalm', 'volhardend'],
  'kameleon': ['verandering', 'aanpasbaar', 'geduldig', 'waarnemer', 'uniek', 'camouflage', 'kleurrijk', 'langzaam', 'draaiend', 'wachtend'],
  'wolf': ['roedel', 'huilen', 'loyaal', 'nachtelijk', 'wild', 'jagend', 'familie', 'woest', 'sociaal', 'maan'],
  'beer': ['winterslaap', 'sterk', 'eenzaam', 'beschermend', 'bos', 'woest', 'knuffel', 'honing', 'krachtig', 'moederlijk'],
  'leeuw': ['trots', 'leider', 'majestueus', 'familie', 'savanne', 'brullen', 'dapper', 'lui', 'koning', 'krachtig'],
  'tijger': ['strepen', 'eenzaam', 'krachtig', 'sluipend', 'oranje', 'woest', 'bedreigd', 'majestueus', 'jagend', 'territoriaal'],
  'slang': ['stil', 'flexibel', 'koud', 'hypnotisch', 'vervellen', 'glibberend', 'geduldig', 'opgerold', 'mysterieus', 'oud'],
  'uil': ['nachtelijk', 'wijs', 'stil', 'draaien', 'waarnemer', 'roepend', 'mysterieus', 'jagend', 'geduldig', 'waakzaam'],
  'walvis': ['enorm', 'vredig', 'diep', 'oud', 'zingend', 'majestueus', 'zachtaardig', 'migratie', 'ademend', 'sierlijk'],
  'neushoorn': ['gepantserd', 'bedreigd', 'krachtig', 'prehistorisch', 'aanvallend', 'eenzaam', 'dik', 'territoriaal', 'stoffig', 'massief'],
  'struisvogel': ['snel', 'lang', 'niet-vliegend', 'nieuwsgierig', 'woestijn', 'rennend', 'elegant', 'nerveus', 'trots', 'afrikaans'],
  'bever': ['bouwer', 'druk', 'ijverig', 'dam', 'nachtelijk', 'familie', 'waterdicht', 'engineering', 'geduldig', 'zwemmend'],
  'vleermuis': ['nachtelijk', 'echolocatie', 'hangend', 'vliegend', 'grot', 'mysterieus', 'halloween', 'koloniaal', 'navigerend', 'stil'],
  'bij': ['druk', 'ijverig', 'kolonie', 'zoemend', 'gouden', 'essentieel', 'georganiseerd', 'zoet', 'bestuivend', 'sociaal'],
  'spin': ['geduldig', 'creatief', 'angst', 'stil', 'hoek', 'wachtend', 'ingewikkeld', 'delicaat', 'roofdier', 'nachtelijk'],
  'krab': ['zijwaarts', 'gepantserd', 'strand', 'defensief', 'knijpend', 'verstoppend', 'kust', 'scharrelen', 'zanderig', 'oud'],
  'kwal': ['drijvend', 'transparant', 'oud', 'sierlijk', 'pijnlijk', 'zwevend', 'lichtgevend', 'delicaat', 'mysterieus', 'stil'],
  'paard': ['majestueus', 'vrijheid', 'loyaal', 'galopperen', 'krachtig', 'sierlijk', 'wild', 'metgezel', 'racen', 'elegant'],
  'konijn': ['zacht', 'snel', 'timide', 'fokken', 'huppelen', 'pluizig', 'schattig', 'lente', 'nerveus', 'zachtaardig'],
  'muis': ['klein', 'snel', 'stil', 'timide', 'nieuwsgierig', 'piepend', 'stiekem', 'nachtelijk', 'knabbelend', 'verstoppend'],
  'kat': ['onafhankelijk', 'nieuwsgierig', 'sierlijk', 'nachtelijk', 'mysterieus', 'zacht', 'elegant', 'lui', 'spinnend', 'jagend'],
  'hond': ['loyaal', 'trouw', 'speels', 'beschermend', 'metgezel', 'opgewonden', 'blij', 'onvoorwaardelijk', 'kwispelen', 'vriendelijk'],
  'papegaai': ['kleurrijk', 'pratend', 'exotisch', 'intelligent', 'luid', 'tropisch', 'imiterend', 'sociaal', 'levendig', 'speels'],
  'toekan': ['kleurrijk', 'tropisch', 'exotisch', 'opvallend', 'nieuwsgierig', 'regenwoud', 'helder', 'onderscheidend', 'speels', 'luid'],
  'pelikaan': ['geduldig', 'duikend', 'kust', 'vissend', 'sierlijk', 'groot', 'zak', 'drijvend', 'elegant', 'geduldig'],
  'zwaan': ['elegant', 'sierlijk', 'romantisch', 'wit', 'vredig', 'glijdend', 'trots', 'ballet', 'majestueus', 'loyaal'],
  'otter': ['speels', 'schattig', 'drijvend', 'sociaal', 'slim', 'zwemmend', 'familie', 'vreugdevol', 'glijdend', 'harig'],
  'zeehond': ['speels', 'glad', 'kust', 'blaffend', 'zwemmend', 'sociaal', 'nieuwsgierig', 'zonnend', 'sierlijk', 'klappend'],

  // === FOOD (Eten - 50 words) ===
  'pizza': ['delen', 'feest', 'rond', 'heet', 'favoriet', 'vrijdag', 'kaasachtig', 'troost', 'punten', 'bezorging'],
  'hamburger': ['snel', 'sappig', 'amerikaans', 'bevredigend', 'lagen', 'gegrild', 'klassiek', 'slordig', 'achtertuin', 'troost'],
  'spaghetti': ['draaien', 'italiaans', 'lang', 'romantisch', 'traditioneel', 'troost', 'slordig', 'saus', 'familie', 'diner'],
  'sushi': ['vers', 'kunst', 'japans', 'delicaat', 'rauw', 'elegant', 'gezond', 'creatief', 'verfijnd', 'ceremonieel'],
  'taco': ['feest', 'mexicaans', 'pittig', 'gevuld', 'knapperig', 'feestelijk', 'dinsdag', 'kleurrijk', 'slordig', 'straat'],
  'pannenkoeken': ['ontbijt', 'luchtig', 'zoet', 'zondag', 'familie', 'lui', 'gestapeld', 'troost', 'ochtend', 'kindertijd'],
  'chocolade': ['verleiding', 'zoet', 'cadeau', 'troost', 'gesmolten', 'verwennend', 'romantisch', 'hunkering', 'rijk', 'geluk'],
  'watermeloen': ['zomer', 'verfrissend', 'pitten', 'rood', 'sappig', 'picknick', 'zoet', 'verkoelend', 'strand', 'slordig'],
  'ananas': ['tropisch', 'zuur', 'stekelig', 'exotisch', 'geel', 'zoet', 'zonnig', 'vakantie', 'verfrissend', 'cocktail'],
  'avocado': ['romig', 'gezond', 'groen', 'trendy', 'toast', 'millennial', 'glad', 'veelzijdig', 'vers', 'brunch'],
  'croissant': ['frans', 'bladerdeeg', 'boter', 'ontbijt', 'koffie', 'elegant', 'gelaagd', 'halvemaan', 'parijse', 'warm'],
  'burrito': ['gerold', 'vulling', 'mexicaans', 'gevuld', 'groot', 'bevredigend', 'gewikkeld', 'draagbaar', 'stevig', 'laat'],
  'lasagne': ['lagen', 'italiaans', 'oven', 'familie', 'stevig', 'troost', 'zondag', 'kaasachtig', 'traditioneel', 'oma'],
  'taart': ['viering', 'zoet', 'verjaardag', 'versierd', 'kaarsjes', 'feest', 'speciaal', 'feestelijk', 'glazuur', 'wens'],
  'pretzel': ['gedraaid', 'zout', 'duits', 'knapperig', 'festival', 'snack', 'oktoberfest', 'bruin', 'zacht', 'straat'],
  'popcorn': ['bioscoop', 'knapperig', 'zout', 'delen', 'film', 'boter', 'verslavend', 'knallend', 'entertainment', 'kermis'],
  'empanada': ['gevuld', 'goudbruin', 'warm', 'huisgemaakt', 'traditie', 'troost', 'handgrootte', 'hartig', 'knapperig', 'familie'],
  'wafel': ['vakjes', 'ontbijt', 'belgisch', 'zoet', 'knapperig', 'brunch', 'siroop', 'luchtig', 'verwennend', 'zondag'],
  'boterham': ['snel', 'praktisch', 'lagen', 'lunch', 'picknick', 'draagbaar', 'dagelijks', 'simpel', 'bevredigend', 'gestapeld'],
  'nachos': ['knapperig', 'delen', 'mexicaans', 'feest', 'gesmolten', 'beladen', 'kaasachtig', 'sportdag', 'slordig', 'feestelijk'],
  'paella': ['spaans', 'geel', 'familie', 'zondag', 'feestelijk', 'zeevrucht', 'traditioneel', 'saffraan', 'samenzijn', 'kust'],
  'stroopwafel': ['zoet', 'plakkerig', 'koffie', 'hollands', 'warm', 'karamel', 'traditioneel', 'knapperig', 'authentiek', 'troost'],
  'bitterballen': ['feest', 'warm', 'borrel', 'hollands', 'knapperig', 'romig', 'gezellig', 'traditioneel', 'snack', 'gouden'],
  'poffertjes': ['klein', 'zoet', 'poeder', 'markt', 'traditie', 'luchtig', 'hollands', 'kindertijd', 'kermis', 'boter'],
  'ijs': ['koud', 'zomer', 'romig', 'zoet', 'smelt', 'kindertijd', 'hoorn', 'verfrissend', 'verwennend', 'traktatie'],
  'pudding': ['zacht', 'karamel', 'wiebelen', 'dessert', 'romig', 'troostend', 'glad', 'kindertijd', 'zoet', 'bibberend'],
  'salade': ['vers', 'gezond', 'groen', 'knapperig', 'licht', 'dieet', 'kleurrijk', 'zomer', 'schoon', 'deugdzaam'],
  'soep': ['warm', 'troostend', 'winter', 'huisgemaakt', 'lepel', 'genezend', 'gezellig', 'regenachtig', 'kalmerend', 'oma'],
  'rijst': ['basis', 'veelzijdig', 'aziatisch', 'wit', 'bijgerecht', 'hoofdvoedsel', 'simpel', 'luchtig', 'essentieel', 'graan'],
  'kip': ['veelzijdig', 'familie', 'zondag', 'betaalbaar', 'gewoon', 'troost', 'geroosterd', 'gouden', 'knapperig', 'klassiek'],
  'mango': ['tropisch', 'zoet', 'sappig', 'zomer', 'exotisch', 'oranje', 'geurig', 'vakantie', 'slordig', 'rijp'],
  'aardbei': ['zoet', 'rood', 'romantisch', 'zomer', 'vers', 'geurig', 'delicaat', 'dessert', 'lente', 'sappig'],
  'banaan': ['geel', 'zoet', 'energie', 'draagbaar', 'ontbijt', 'tropisch', 'glad', 'gezond', 'snel', 'rijp'],
  'druif': ['zoet', 'klein', 'wijngaard', 'snacken', 'sappig', 'tros', 'wijn', 'paars', 'verfrissend', 'knappen'],
  'kers': ['rood', 'zoet', 'zomer', 'steeltje', 'dessert', 'romantisch', 'klein', 'glanzend', 'delicaat', 'zuur'],
  'kaas': ['gerijpt', 'rijk', 'wijn', 'hartig', 'gesmolten', 'troost', 'zuivel', 'variëteit', 'combinatie', 'romig'],
  'ham': ['hartig', 'feestdag', 'traditioneel', 'gerookt', 'gesneden', 'kerst', 'gezouten', 'zout', 'ontbijt', 'broodje'],
  'spek': ['knapperig', 'hartig', 'ontbijt', 'verslavend', 'sissend', 'rokerig', 'verwennend', 'zout', 'amerikaans', 'troost'],
  'ei': ['ontbijt', 'veelzijdig', 'basis', 'eiwit', 'ochtend', 'essentieel', 'simpel', 'brunch', 'breekbaar', 'voedzaam'],
  'brood': ['basis', 'warm', 'vers', 'troost', 'thuis', 'hoofdvoedsel', 'korst', 'geroosterd', 'essentieel', 'bakken'],
  'koekje': ['zoet', 'traktatie', 'bakken', 'kindertijd', 'troost', 'snack', 'kruimelig', 'huisgemaakt', 'beloning', 'melk'],
  'donut': ['zoet', 'rond', 'geglazuurd', 'traktatie', 'koffie', 'ochtend', 'gat', 'hagelslag', 'verwennend', 'troost'],
  'brownie': ['chocolade', 'rijk', 'chewy', 'verwennend', 'vierkant', 'bakken', 'smeuïg', 'troost', 'warm', 'decadent'],
  'gelei': ['wiebelig', 'zoet', 'kleurrijk', 'kindertijd', 'bibberend', 'fruitig', 'leuk', 'dessert', 'veerkrachtig', 'transparant'],
  'snoep': ['zoet', 'traktatie', 'kleurrijk', 'kindertijd', 'halloween', 'suiker', 'verpakking', 'verwennend', 'hunkering', 'verboden'],
  'koffie': ['ochtend', 'energie', 'ritueel', 'aromatisch', 'bitter', 'essentieel', 'werk', 'verslavend', 'warm', 'ontwaken'],
  'limonade': ['zomer', 'verfrissend', 'zuur', 'zoet', 'koud', 'kindertijd', 'kraam', 'geel', 'dorst', 'zonneschijn'],
  'smoothie': ['gezond', 'gemengd', 'ontbijt', 'energie', 'vers', 'fruitig', 'dik', 'kleurrijk', 'workout', 'vitamines'],
  'omelet': ['ontbijt', 'eieren', 'luchtig', 'gevuld', 'frans', 'brunch', 'gevouwen', 'hartig', 'snel', 'ochtend'],
  'kroket': ['knapperig', 'gouden', 'gefrituurd', 'romig', 'hartig', 'snack', 'voorgerecht', 'troost', 'knapperig', 'traditioneel'],

  // === PLACES (Plaatsen - 50 words) ===
  'strand': ['ontspannend', 'zomer', 'zand', 'vakantie', 'horizon', 'golven', 'vredig', 'zonsondergang', 'ontsnappen', 'zout'],
  'berg': ['uitdagend', 'frisse lucht', 'hoogte', 'avontuur', 'stilte', 'vredig', 'majestueus', 'klimmen', 'top', 'uitzichten'],
  'bibliotheek': ['stilte', 'kennis', 'rustig', 'concentratie', 'orde', 'studie', 'toevlucht', 'wijsheid', 'stil', 'stoffig'],
  'ziekenhuis': ['steriel', 'zorgen', 'hoop', 'urgent', 'zorg', 'genezen', 'angst', 'wit', 'klinisch', 'wachten'],
  'vliegveld': ['wachten', 'afscheid', 'vroeg', 'bagage', 'zenuwen', 'opwinding', 'vertragingen', 'vertrek', 'hereniging', 'druk'],
  'museum': ['geschiedenis', 'stilte', 'bewondering', 'cultuur', 'oud', 'wandelen', 'ontdekking', 'stilte', 'educatief', 'contemplatie'],
  'stadion': ['spanning', 'menigte', 'juichen', 'passie', 'overwinning', 'gejuich', 'eenheid', 'adrenaline', 'zingen', 'sfeer'],
  'restaurant': ['viering', 'bediening', 'wachten', 'elegant', 'afspraakje', 'speciaal', 'sfeer', 'romantiek', 'verwennend', 'gelegenheid'],
  'casino': ['geluk', 'risico', 'lichten', 'nachtelijk', 'verleiding', 'opwinding', 'glitter', 'kans', 'spanning', 'fortuin'],
  'dierentuin': ['familie', 'leerzaam', 'opgesloten', 'kijken', 'weekend', 'kindertijd', 'behoud', 'wandelen', 'ontdekking', 'fascinatie'],
  'park': ['familie', 'wandeling', 'groen', 'kinderen', 'rust', 'vredig', 'zonnig', 'picknick', 'ontsnappen', 'natuur'],
  'bioscoop': ['donker', 'popcorn', 'ontsnappen', 'stilte', 'scherm', 'verwachting', 'meeslepend', 'comfortabel', 'afspraakje', 'entertainment'],
  'theater': ['dramatisch', 'elegant', 'applaus', 'cultuur', 'gordijn', 'emoties', 'live', 'artistiek', 'verfijnd', 'avond'],
  'kerk': ['stilte', 'vrede', 'bezinning', 'zondag', 'gemeenschap', 'spiritueel', 'heilig', 'plechtigheid', 'contemplatie', 'klokken'],
  'supermarkt': ['lijstje', 'vergelijken', 'karretjes', 'routine', 'rij', 'keuzes', 'wekelijks', 'druk', 'tl-licht', 'alledaags'],
  'school': ['leren', 'vrienden', 'routine', 'bel', 'herinneringen', 'kindertijd', 'groei', 'huiswerk', 'speelplaats', 'vormend'],
  'universiteit': ['vrijheid', 'examens', 'toekomst', 'onafhankelijk', 'studeren', 'groei', 'vrienden', 'uitdagend', 'kansen', 'jeugd'],
  'sportschool': ['inspanning', 'zweet', 'discipline', 'spiegels', 'routine', 'vooruitgang', 'motivatie', 'transformatie', 'toewijding', 'energie'],
  'zwembad': ['verfrissend', 'zomer', 'chloor', 'duiken', 'drijven', 'ontspanning', 'plons', 'baantjes', 'verkoelend', 'ontspanning'],
  'tuin': ['vrede', 'kleuren', 'verzorging', 'lente', 'geuren', 'groei', 'geduld', 'schoonheid', 'koesteren', 'ontsnappen'],
  'plein': ['ontmoeting', 'gemeenschap', 'rusten', 'duiven', 'centrum', 'sociaal', 'samenzijn', 'zonnig', 'fontein', 'bankjes'],
  'markt': ['drukte', 'kleuren', 'vers', 'onderhandelen', 'geuren', 'lokaal', 'levendig', 'authentiek', 'chaos', 'ontdekking'],
  'station': ['wachten', 'aankomst', 'afscheid', 'roosters', 'reizigers', 'omroep', 'haasten', 'reizen', 'drukte', 'vertrek'],
  'haven': ['zoute lucht', 'handel', 'meeuwen', 'horizon', 'vertrek', 'boten', 'vissen', 'avontuur', 'maritiem', 'nostalgisch'],
  'vuurtoren': ['gids', 'eenzaam', 'nachtelijk', 'hoog', 'veiligheid', 'romantisch', 'kust', 'baken', 'geïsoleerd', 'hoop'],
  'kasteel': ['middeleeuws', 'mysterieus', 'steen', 'historisch', 'fantasie', 'romantisch', 'groots', 'koninklijk', 'oud', 'sprookje'],
  'paleis': ['luxe', 'groots', 'historisch', 'elegant', 'macht', 'koninklijk', 'weelderig', 'majestueus', 'ceremonieel', 'verguld'],
  'piramide': ['oud', 'mysterieus', 'driehoekig', 'monumentaal', 'woestijn', 'eeuwig', 'raadselachtig', 'massief', 'heilig', 'tijdloos'],
  'grot': ['donker', 'koud', 'mysterieus', 'echo', 'ontdekken', 'oud', 'verborgen', 'druipend', 'formaties', 'oer'],
  'vulkaan': ['gevaarlijk', 'krachtig', 'heet', 'slapend', 'imposant', 'verwoestend', 'majestueus', 'oer', 'rook', 'rommelend'],
  'aquarium': ['blauw', 'vredig', 'kijken', 'educatief', 'kleurrijk', 'onderwater', 'gloeiend', 'betoverend', 'stil', 'verwondering'],
  'circus': ['kleurrijk', 'magisch', 'kindertijd', 'opwinding', 'verwondering', 'nostalgisch', 'vermakelijk', 'spektakel', 'lichten', 'happen'],
  'discotheek': ['luid', 'donker', 'vol', 'dansen', 'nachtelijk', 'energie', 'pulseren', 'sociaal', 'lichten', 'vibreren'],
  'cafetaria': ['snel', 'lunch', 'vol', 'casual', 'druk', 'dienbladen', 'tl-licht', 'routine', 'lawaaierig', 'praktisch'],
  'bakkerij': ['aromatisch', 'warm', 'vers', 'verleidelijk', 'ochtend', 'gezellig', 'zoet', 'traditioneel', 'gouden', 'troost'],
  'apotheek': ['steriel', 'behulpzaam', 'gezondheid', 'wit', 'verlichting', 'recepten', 'klinisch', 'wachten', 'remedies', 'essentieel'],
  'bank': ['formeel', 'veilig', 'stil', 'wachten', 'serieus', 'marmer', 'intimiderend', 'betrouwbaar', 'koud', 'institutioneel'],
  'kantoor': ['routine', 'werk', 'tl-licht', 'vergaderingen', 'stress', 'deadlines', 'hokjes', 'professioneel', 'koffie', 'repetitief'],
  'fabriek': ['luid', 'industrieel', 'repetitief', 'productief', 'machines', 'shift', 'georganiseerd', 'efficiënt', 'mechanisch', 'assemblage'],
  'boerderij': ['vredig', 'landelijk', 'hard werken', 'dageraad', 'dieren', 'vers', 'simpel', 'seizoenen', 'oogst', 'platteland'],
  'begraafplaats': ['stil', 'vredig', 'reflecterend', 'plechtig', 'eeuwig', 'bezoek', 'herinneringen', 'stilte', 'respect', 'contemplatie'],
  'gevangenis': ['opgesloten', 'geïsoleerd', 'koud', 'routine', 'beperkt', 'grijs', 'gecontroleerd', 'imposant', 'hard', 'institutioneel'],
  'ambassade': ['formeel', 'diplomatiek', 'veilig', 'officieel', 'internationaal', 'bureaucratisch', 'wachten', 'vlaggen', 'serieus', 'beschermd'],
  'kathedraal': ['majestueus', 'spiritueel', 'oud', 'indrukwekkend', 'vredig', 'torenhoog', 'heilig', 'artistiek', 'plechtig', 'echoënd'],
  'moskee': ['vredig', 'spiritueel', 'gemeenschap', 'devotie', 'sereen', 'heilig', 'oproep', 'rustig', 'meditatief', 'eerbiedig'],
  'tempel': ['heilig', 'oud', 'vredig', 'spiritueel', 'meditatief', 'sereen', 'devotie', 'wierook', 'bellen', 'contemplatie'],
  'klooster': ['stil', 'geïsoleerd', 'spiritueel', 'vredig', 'simpel', 'devotie', 'oud', 'contemplatief', 'sereen', 'sober'],
  'sterrenwacht': ['donker', 'stil', 'verwondering', 'wetenschappelijk', 'nachtelijk', 'afgelegen', 'sterrenkijken', 'ontdekking', 'kosmisch', 'ontzag'],
  'planetarium': ['verwondering', 'educatief', 'donker', 'meeslepend', 'kosmisch', 'fascinerend', 'koepel', 'contemplatief', 'sterren', 'magisch'],
  'klif': ['duizelingwekkend', 'gevaarlijk', 'uitzichten', 'wind', 'dramatisch', 'rand', 'kust', 'majestueus', 'durvend', 'adembenemend'],

  // === PROFESSIONS (Beroepen - 50 words) ===
  'dokter': ['witte jas', 'zorgzaam', 'vertrouwen', 'studeren', 'roeping', 'toewijding', 'verantwoordelijkheid', 'genezen', 'empathie', 'lange uren'],
  'brandweerman': ['dapper', 'noodgeval', 'sirene', 'held', 'rood', 'moed', 'onbaatzuchtig', 'redden', 'adrenaline', 'beschermend'],
  'astronaut': ['avontuur', 'training', 'geïsoleerd', 'pionier', 'droom', 'moedig', 'elite', 'zwevend', 'ontdekker', 'verwondering'],
  'kok': ['creatief', 'druk', 'smaken', 'passie', 'hitte', 'artistiek', 'precies', 'veeleisend', 'toegewijd', 'perfectionist'],
  'piloot': ['verantwoordelijkheid', 'reizen', 'uniform', 'hoogte', 'controle', 'kalm', 'precisie', 'getraind', 'avontuurlijk', 'gerespecteerd'],
  'leraar': ['geduld', 'roeping', 'invloed', 'bord', 'toekomst', 'toewijding', 'inspirerend', 'koesterend', 'vormend', 'bevredigend'],
  'detective': ['oplettend', 'nieuwsgierig', 'logisch', 'mysterie', 'aanwijzingen', 'volhardend', 'intuïtief', 'analytisch', 'vragend', 'methodisch'],
  'architect': ['visie', 'creatief', 'tekeningen', 'ruimtes', 'ontwerp', 'artistiek', 'precies', 'fantasierijk', 'structureel', 'innovatief'],
  'chirurg': ['precisie', 'druk', 'vaste handen', 'concentratie', 'lange uren', 'besluitvaardig', 'bekwaam', 'gefocust', 'kalm', 'veeleisend'],
  'muzikant': ['expressief', 'oefenen', 'emotioneel', 'talent', 'podium', 'toegewijd', 'gepassioneerd', 'artistiek', 'creatief', 'gedisciplineerd'],
  'advocaat': ['argumenten', 'formeel', 'verdediging', 'rechtvaardigheid', 'woorden', 'analytisch', 'overtuigend', 'strategisch', 'nauwgezet', 'competitief'],
  'politieagent': ['bescherming', 'orde', 'uniform', 'gemeenschap', 'patrouille', 'plicht', 'dienst', 'waakzaam', 'moedig', 'autoriteit'],
  'dierenarts': ['mededogen', 'dieren', 'zorgzaam', 'roeping', 'geduld', 'zachtaardig', 'toegewijd', 'genezend', 'empathisch', 'bevredigend'],
  'journalist': ['nieuwsgierig', 'snel', 'waarheid', 'nieuws', 'onderzoeken', 'volhardend', 'vragend', 'deadline', 'verhalen', 'informeren'],
  'ingenieur': ['analytisch', 'oplossingen', 'logisch', 'bouwen', 'berekenen', 'precies', 'innovatief', 'probleemoplossend', 'technisch', 'systematisch'],
  'tandarts': ['precisie', 'hygiëne', 'zenuwen', 'glimlachen', 'controle', 'nauwgezet', 'zachtaardig', 'professioneel', 'routine', 'preventie'],
  'verpleegster': ['zorgzaam', 'nachtdienst', 'mededogen', 'uitputtend', 'toegewijd', 'empathisch', 'hardwerkend', 'geduldig', 'essentieel', 'ondersteunend'],
  'fotograaf': ['oplettend', 'moment', 'licht', 'creativiteit', 'perspectief', 'artistiek', 'geduldig', 'vastleggen', 'verhalen', 'visueel'],
  'schilder': ['creatief', 'kleuren', 'expressief', 'eenzaam', 'inspiratie', 'artistiek', 'fantasierijk', 'gepassioneerd', 'oplettend', 'visueel'],
  'acteur': ['veelzijdig', 'emotioneel', 'onthouden', 'zenuwen', 'applaus', 'transformatief', 'expressief', 'gedisciplineerd', 'kwetsbaar', 'charismatisch'],
  'zanger': ['emotioneel', 'podium', 'repetitie', 'zenuwen', 'microfoon', 'expressief', 'gepassioneerd', 'gedisciplineerd', 'krachtig', 'kwetsbaar'],
  'danser': ['discipline', 'gratie', 'fysiek', 'expressief', 'repetitie', 'artistiek', 'gepassioneerd', 'atletisch', 'elegant', 'toegewijd'],
  'schrijver': ['eenzaam', 'fantasierijk', 'oplettend', 'discipline', 'koffie', 'creatief', 'introspectief', 'geduldig', 'deadline', 'geïnspireerd'],
  'wetenschapper': ['nieuwsgierig', 'methodisch', 'geduldig', 'ontdekking', 'laboratorium', 'analytisch', 'toegewijd', 'innovatief', 'vragend', 'volhardend'],
  'programmeur': ['logisch', 'nachtelijk', 'probleem', 'koffie', 'creatief', 'geduldig', 'analytisch', 'gefocust', 'debuggen', 'innovatief'],
  'monteur': ['praktisch', 'vuil', 'diagnose', 'gereedschap', 'repareren', 'bekwaam', 'geduldig', 'methodisch', 'deskundig', 'hands-on'],
  'elektricien': ['voorzichtig', 'technisch', 'draden', 'gevaarlijk', 'repareren', 'precies', 'bekwaam', 'essentieel', 'deskundig', 'probleemoplossend'],
  'timmerman': ['traditioneel', 'hout', 'meten', 'creatief', 'gereedschap', 'bekwaam', 'precies', 'geduldig', 'vakmanschap', 'artistiek'],
  'bakker': ['vroeg opstaan', 'geur', 'warmte', 'traditioneel', 'deeg', 'creatief', 'precies', 'geduldig', 'troostend', 'bevredigend'],
  'tuinman': ['geduldig', 'natuur', 'seizoenen', 'verzorging', 'rustig', 'koesterend', 'toegewijd', 'buiten', 'therapeutisch', 'groei'],
  'bibliothecaris': ['stil', 'deskundig', 'georganiseerd', 'behulpzaam', 'geduldig', 'toegewijd', 'geleerd', 'bewarend', 'begeleidend', 'gecultiveerd'],
  'archeoloog': ['geduldig', 'nieuwsgierig', 'avontuurlijk', 'ontdekking', 'stoffig', 'nauwgezet', 'historisch', 'toegewijd', 'ontdekker', 'volhardend'],
  'bioloog': ['nieuwsgierig', 'oplettend', 'geduldig', 'natuur', 'ontdekking', 'analytisch', 'toegewijd', 'veldwerk', 'systematisch', 'gepassioneerd'],
  'scheikundige': ['precies', 'analytisch', 'methodisch', 'laboratorium', 'nieuwsgierig', 'experimenteel', 'voorzichtig', 'innovatief', 'systematisch', 'ontdekking'],
  'natuurkundige': ['analytisch', 'nieuwsgierig', 'theoretisch', 'wiskundig', 'innovatief', 'abstract', 'vragend', 'toegewijd', 'volhardend', 'visionair'],
  'psycholoog': ['empathisch', 'luisterend', 'geduldig', 'inzichtelijk', 'analytisch', 'begripvol', 'ondersteunend', 'objectief', 'opmerkzaam', 'toegewijd'],
  'socioloog': ['oplettend', 'analytisch', 'nieuwsgierig', 'vragend', 'systematisch', 'inzichtelijk', 'objectief', 'onderzoek', 'patronen', 'begripvol'],
  'econoom': ['analytisch', 'voorspellend', 'cijfers', 'trends', 'strategisch', 'methodisch', 'voorspellend', 'systematisch', 'geïnformeerd', 'adviserend'],
  'accountant': ['precies', 'georganiseerd', 'cijfers', 'methodisch', 'deadline', 'analytisch', 'nauwgezet', 'betrouwbaar', 'systematisch', 'detail'],
  'bankier': ['formeel', 'cijfers', 'betrouwbaar', 'analytisch', 'strategisch', 'professioneel', 'conservatief', 'adviserend', 'berekend', 'serieus'],
  'kapper': ['creatief', 'sociaal', 'transformerend', 'artistiek', 'trendy', 'zelfverzekerd', 'persoonlijk', 'bekwaam', 'modieus', 'luisterend'],
  'kleermaker': ['precies', 'traditioneel', 'geduldig', 'bekwaam', 'nauwgezet', 'artistiek', 'vakmanschap', 'detail', 'elegant', 'op maat'],
  'schoenmaker': ['traditioneel', 'geduldig', 'vakmanschap', 'bekwaam', 'nauwgezet', 'artistiek', 'kwaliteit', 'detail', 'ambacht', 'toegewijd'],
  'juwelier': ['precies', 'artistiek', 'geduldig', 'bekwaam', 'nauwgezet', 'creatief', 'elegant', 'vakmanschap', 'detail', 'luxueus'],
  'horlogemaker': ['precies', 'geduldig', 'nauwgezet', 'bekwaam', 'traditioneel', 'detail', 'vakmanschap', 'ingewikkeld', 'toegewijd', 'gefocust'],
  'zeeman': ['avontuurlijk', 'veerkrachtig', 'ervaren', 'weer', 'eenzaam', 'traditioneel', 'taai', 'deskundig', 'dapper', 'zwervend'],
  'visser': ['geduldig', 'vroeg opstaan', 'weer', 'traditioneel', 'eenzaam', 'veerkrachtig', 'hardwerkend', 'deskundig', 'simpel', 'taai'],
  'boer': ['hardwerkend', 'vroeg', 'seizoenen', 'geduldig', 'traditioneel', 'veerkrachtig', 'toegewijd', 'koesterend', 'verbonden', 'essentieel'],
  'veehouder': ['ruig', 'vroeg', 'buiten', 'traditioneel', 'hardwerkend', 'veerkrachtig', 'geduldig', 'toegewijd', 'onafhankelijk', 'taai'],
  'mijnwerker': ['gevaarlijk', 'hard werk', 'donker', 'taai', 'toegewijd', 'ondergronds', 'veerkrachtig', 'fysiek', 'essentieel', 'stoffig'],

  // === MOVIES (Films - 50 words) ===
  'titanic': ['tragisch', 'romantisch', 'koud', 'onvergetelijk', 'klassiek', 'episch', 'hartverscheurend', 'emotioneel', 'iconisch', 'tijdloos'],
  'avatar': ['fantastisch', 'blauw', 'natuur', 'technologie', 'andere wereld', 'meeslepend', 'visueel', 'episch', 'revolutionair', 'milieu'],
  'frozen': ['koud', 'musical', 'zussen', 'magie', 'bevrijding', 'emotioneel', 'versterkend', 'catchy', 'mooi', 'bevrijdend'],
  'jaws': ['angst', 'zomer', 'water', 'spanning', 'klassiek', 'gespannen', 'angstaanjagend', 'iconisch', 'spannend', 'legendarisch'],
  'batman': ['donker', 'nachtelijk', 'gerechtigheid', 'eenzaam', 'wraak', 'somber', 'mysterieus', 'heroïsch', 'complex', 'vigilant'],
  'shrek': ['anders', 'humor', 'vriendschap', 'moeras', 'lagen', 'onconventioneel', 'hartverwarmend', 'satirisch', 'lief', 'accepterend'],
  'inception': ['verwarrend', 'dromen', 'labyrint', 'diep', 'plot twist', 'verbijsterend', 'gelaagd', 'complex', 'briljant', 'filosofisch'],
  'gladiator': ['episch', 'wraak', 'arena', 'eer', 'oud', 'krachtig', 'emotioneel', 'heroïsch', 'brutaal', 'triomfantelijk'],
  'matrix': ['filosofisch', 'werkelijkheid', 'keuze', 'revolutionair', 'zwart', 'verbijsterend', 'iconisch', 'baanbrekend', 'dystopisch', 'tot nadenken'],
  'coco': ['familie', 'muziek', 'traditie', 'kleurrijk', 'herinneringen', 'emotioneel', 'mooi', 'cultureel', 'hartverwarmend', 'ontroerend'],
  'up': ['avontuur', 'emotioneel', 'dromen', 'ballonnen', 'vriendschap', 'hartverwarmend', 'ontroerend', 'nostalgisch', 'inspirerend', 'tranen'],
  'ratatouille': ['ambities', 'koken', 'klein', 'dromen', 'frankrijk', 'inspirerend', 'hartverwarmend', 'artistiek', 'underdog', 'heerlijk'],
  'toy story': ['kindertijd', 'vriendschap', 'nostalgie', 'loyaliteit', 'avontuur', 'fantasierijk', 'hartverwarmend', 'pionier', 'emotioneel', 'tijdloos'],
  'finding nemo': ['familie', 'oceaan', 'avontuur', 'doorzettingsvermogen', 'kleurrijk', 'emotioneel', 'ontroerend', 'mooi', 'hartverwarmend', 'vastberaden'],
  'cars': ['snelheid', 'vriendschap', 'bescheidenheid', 'landelijk', 'racen', 'nostalgisch', 'hartverwarmend', 'verlossing', 'kleurrijk', 'amerikaans'],
  'moana': ['oceaan', 'avontuur', 'identiteit', 'dapper', 'musical', 'versterkend', 'mooi', 'inspirerend', 'cultureel', 'episch'],
  'encanto': ['familie', 'magie', 'uniek', 'musical', 'colombiaans', 'kleurrijk', 'emotioneel', 'mooi', 'inclusief', 'versterkend'],
  'spider-man': ['verantwoordelijkheid', 'jong', 'stad', 'geheim', 'behendig', 'herkenbaar', 'heroïsch', 'conflicterend', 'iconisch', 'coming-of-age'],
  'iron man': ['technologie', 'genie', 'arrogant', 'transformatie', 'metaal', 'charismatisch', 'verlossing', 'grappig', 'heroïsch', 'futuristisch'],
  'thor': ['mythologie', 'kracht', 'familie', 'held', 'noors', 'majestueus', 'arrogant', 'humoristisch', 'episch', 'goddelijk'],
  'jurassic park': ['prehistorisch', 'gevaar', 'wetenschap', 'avontuur', 'eiland', 'spannend', 'baanbrekend', 'angstaanjagend', 'ontzagwekkend', 'iconisch'],
  'harry potter': ['magie', 'vriendschap', 'lot', 'mysterie', 'school', 'betoverend', 'episch', 'nostalgisch', 'fantasierijk', 'geliefd'],
  'star wars': ['episch', 'familie', 'lot', 'melkweg', 'klassiek', 'legendarisch', 'iconisch', 'mythisch', 'avontuurlijk', 'tijdloos'],
  'the godfather': ['familie', 'macht', 'loyaliteit', 'donker', 'klassiek', 'legendarisch', 'iconisch', 'complex', 'meesterlijk', 'invloedrijk'],
  'forrest gump': ['onschuldig', 'historisch', 'rennen', 'lot', 'liefde', 'ontroerend', 'inspirerend', 'nostalgisch', 'hartverwarmend', 'iconisch'],
  'rocky': ['inspanning', 'underdog', 'inspirerend', 'training', 'vechten', 'vastberadenheid', 'iconisch', 'triomfantelijk', 'emotioneel', 'motiverend'],
  'rambo': ['overleven', 'eenling', 'jungle', 'actie', 'trauma', 'intens', 'gewelddadig', 'heroïsch', 'iconisch', 'strijder'],
  'terminator': ['toekomst', 'onstopbaar', 'metaal', 'achtervolging', 'lot', 'iconisch', 'meedogenloos', 'sci-fi', 'intens', 'klassiek'],
  'alien': ['horror', 'geïsoleerd', 'donker', 'overleven', 'ruimte', 'angstaanjagend', 'claustrofobisch', 'intens', 'iconisch', 'baanbrekend'],
  'indiana jones': ['avontuur', 'archeologie', 'gevaar', 'hoed', 'klassiek', 'iconisch', 'grappig', 'opwindend', 'nostalgisch', 'legendarisch'],
  'the lion king': ['familie', 'lot', 'cirkel', 'musical', 'emotioneel', 'majestueus', 'iconisch', 'mooi', 'ontroerend', 'tijdloos'],
  'aladdin': ['magisch', 'avontuur', 'romantisch', 'musical', 'vrijheid', 'kleurrijk', 'leuk', 'memorabel', 'charmant', 'nostalgisch'],
  'mulan': ['eer', 'dapper', 'vermomming', 'familie', 'versterkend', 'inspirerend', 'cultureel', 'sterk', 'emotioneel', 'heroïsch'],
  'tarzan': ['wild', 'identiteit', 'familie', 'jungle', 'avontuur', 'emotioneel', 'romantisch', 'mooi', 'ontroerend', 'atletisch'],
  'pocahontas': ['natuur', 'romantisch', 'historisch', 'musical', 'mooi', 'cultureel', 'emotioneel', 'spiritueel', 'kleurrijk', 'aangrijpend'],
  'hercules': ['mythologie', 'held', 'musical', 'humor', 'avontuur', 'inspirerend', 'leuk', 'kleurrijk', 'romantisch', 'underdog'],
  'dumbo': ['emotioneel', 'onschuldig', 'anders', 'vriendschap', 'ontroerend', 'hartverscheurend', 'nostalgisch', 'magisch', 'inspirerend', 'tranen'],
  'bambi': ['natuur', 'onschuldig', 'emotioneel', 'mooi', 'ontroerend', 'hartverscheurend', 'nostalgisch', 'zachtaardig', 'klassiek', 'tranen'],
  'pinocchio': ['wens', 'moreel', 'avontuur', 'magisch', 'klassiek', 'donker', 'nostalgisch', 'fantasierijk', 'waarschuwend', 'transformatief'],
  'cinderella': ['magisch', 'romantisch', 'transformatie', 'klassiek', 'dromerig', 'betoverend', 'iconisch', 'hoopvol', 'mooi', 'tijdloos'],
  'the little mermaid': ['magisch', 'romantisch', 'musical', 'dromerig', 'onderwater', 'kleurrijk', 'iconisch', 'betoverend', 'nostalgisch', 'avontuurlijk'],
  'interstellar': ['episch', 'emotioneel', 'wetenschappelijk', 'familie', 'verbijsterend', 'visueel prachtig', 'tot nadenken', 'intens', 'diepgaand', 'kosmisch'],
  'dunkirk': ['intens', 'overleven', 'historisch', 'meeslepend', 'spannend', 'heroïsch', 'rauw', 'cinematisch', 'schrijnend', 'grijpend'],
  'joker': ['donker', 'verontrustend', 'psychologisch', 'tragisch', 'transformatief', 'onheilspellend', 'krachtig', 'controversieel', 'rauw', 'achtervolgen'],
  'aquaman': ['onderwater', 'avontuur', 'heroïsch', 'kleurrijk', 'episch', 'leuk', 'visueel', 'mythisch', 'actievol', 'spectaculair'],
  'wonder woman': ['versterkend', 'heroïsch', 'inspirerend', 'sterk', 'mythisch', 'historisch', 'actie', 'iconisch', 'hoopvol', 'strijder'],
  'superman': ['heroïsch', 'iconisch', 'hoopvol', 'krachtig', 'klassiek', 'inspirerend', 'legendarisch', 'nobel', 'onoverwinnelijk', 'tijdloos'],
  'hulk': ['woede', 'transformatie', 'krachtig', 'conflicterend', 'groen', 'verwoestend', 'onbegrepen', 'tragisch', 'ongelooflijk', 'ontketend'],
  'deadpool': ['oneerbiedig', 'grappig', 'gewelddadig', 'meta', 'onconventioneel', 'grof', 'geestig', 'oneerbiedig', 'chaotisch', 'vermakelijk'],
  'venom': ['donker', 'anti-held', 'symbiotisch', 'conflicterend', 'gewelddadig', 'humoristisch', 'chaotisch', 'buitenaards', 'monsterlijk', 'complex'],

  // === SPORTS (Sport - 50 words) ===
  'voetbal': ['passie', 'wereldwijd', 'team', 'zondag', 'doelpunten', 'opwindend', 'competitief', 'mooi', 'verenigend', 'dramatisch'],
  'basketbal': ['lang', 'snel', 'veld', 'amerikaans', 'springen', 'atletisch', 'opwindend', 'ritmisch', 'stedelijk', 'dynamisch'],
  'tennis': ['elegant', 'individueel', 'concentratie', 'wit', 'rally', 'intens', 'precies', 'strategisch', 'sierlijk', 'veeleisend'],
  'zwemmen': ['verfrissend', 'ademhaling', 'discipline', 'vroeg', 'zwembad', 'meditatief', 'eenzaam', 'ritmisch', 'uithoudingsvermogen', 'vredig'],
  'honkbal': ['amerikaans', 'langzaam', 'stadion', 'zomer', 'familie', 'nostalgisch', 'traditioneel', 'strategisch', 'pastoraal', 'iconisch'],
  'volleybal': ['strand', 'team', 'springen', 'zomer', 'net', 'sociaal', 'atletisch', 'leuk', 'dynamisch', 'competitief'],
  'golf': ['geduld', 'stilte', 'groen', 'exclusief', 'rustig', 'strategisch', 'precies', 'ontspannend', 'traditioneel', 'contemplatief'],
  'boksen': ['intens', 'discipline', 'één tegen één', 'zweet', 'ring', 'brutaal', 'moedig', 'oer', 'strategisch', 'veeleisend'],
  'fietsen': ['uithoudingsvermogen', 'landschap', 'vrijheid', 'snelheid', 'heuvels', 'vredig', 'uitdagend', 'bevrijdend', 'ritmisch', 'avontuurlijk'],
  'atletiek': ['basis', 'snelheid', 'baan', 'records', 'inspanning', 'fundamenteel', 'competitief', 'puur', 'veeleisend', 'individueel'],
  'surfen': ['vrijheid', 'golven', 'balans', 'zomer', 'californisch', 'spiritueel', 'uitdagend', 'opwindend', 'natuurlijk', 'bevrijdend'],
  'skiën': ['koud', 'snelheid', 'winter', 'berg', 'wit', 'opwindend', 'elegant', 'uitdagend', 'schilderachtig', 'avontuurlijk'],
  'schaatsen': ['gratie', 'balans', 'ijs', 'elegant', 'pirouettes', 'artistiek', 'precies', 'mooi', 'veeleisend', 'expressief'],
  'karate': ['discipline', 'respect', 'oosters', 'band', 'controle', 'gefocust', 'traditioneel', 'precies', 'mentaal', 'ceremonieel'],
  'judo': ['worpen', 'respect', 'greep', 'oosters', 'mat', 'balans', 'strategisch', 'gedisciplineerd', 'technisch', 'filosofisch'],
  'hockey': ['koud', 'snel', 'team', 'canadees', 'intens', 'fysiek', 'opwindend', 'agressief', 'bekwaam', 'gepassioneerd'],
  'rugby': ['fysiek', 'team', 'modder', 'respect', 'ovaal', 'brutaal', 'broederschap', 'taai', 'gepassioneerd', 'traditioneel'],
  'cricket': ['engels', 'langzaam', 'traditie', 'elegant', 'zomer', 'strategisch', 'gentleman', 'geduldig', 'beschaafd', 'historisch'],
  'badminton': ['snel', 'veer', 'licht', 'aziatisch', 'reflexen', 'behendig', 'precies', 'binnen', 'snel', 'technisch'],
  'tafeltennis': ['snel', 'reflexen', 'klein', 'aziatisch', 'binnen', 'snel', 'precies', 'competitief', 'behendig', 'ritmisch'],
  'klimmen': ['verticaal', 'kracht', 'mentaal', 'avontuur', 'grepen', 'uitdagend', 'eng', 'bevredigend', 'gefocust', 'vastberaden'],
  'parachutespringen': ['adrenaline', 'vallen', 'vrijheid', 'moed', 'lucht', 'opwindend', 'angstaanjagend', 'bevrijdend', 'extreem', 'adembenemend'],
  'duiken': ['stilte', 'diep', 'ademhaling', 'kleuren', 'rust', 'sereen', 'meditatief', 'verkennend', 'gewichtloos', 'andere wereld'],
  'zeilen': ['wind', 'vrijheid', 'geduld', 'horizon', 'stil', 'vredig', 'avontuurlijk', 'traditioneel', 'romantisch', 'uitdagend'],
  'roeien': ['ritme', 'team', 'vroeg', 'water', 'synchroon', 'uithoudingsvermogen', 'vredig', 'veeleisend', 'meditatief', 'elegant'],
  'gymnastiek': ['flexibiliteit', 'gratie', 'perfectie', 'discipline', 'jong', 'artistiek', 'veeleisend', 'elegant', 'precies', 'indrukwekkend'],
  'worstelen': ['oud', 'kracht', 'traditie', 'contact', 'olympisch', 'oer', 'technisch', 'intens', 'veeleisend', 'strategisch'],
  'schermen': ['elegant', 'strategie', 'snel', 'traditie', 'wit', 'precies', 'intellectueel', 'verfijnd', 'behendig', 'eerbaar'],
  'polo': ['exclusief', 'snelheid', 'elegant', 'groen', 'traditie', 'aristocratisch', 'verfijnd', 'opwindend', 'luxueus', 'prestigieus'],
  'paardrijden': ['elegant', 'verbinding', 'discipline', 'traditie', 'platteland', 'vredig', 'sierlijk', 'therapeutisch', 'nobel', 'band'],
  'snowboarden': ['cool', 'jong', 'winter', 'vrijheid', 'berg', 'rebels', 'opwindend', 'stijlvol', 'avontuurlijk', 'extreem'],
  'wakeboarden': ['zomer', 'water', 'balans', 'opwindend', 'jong', 'atletisch', 'leuk', 'uitdagend', 'spannend', 'energiek'],
  'skateboarden': ['stedelijk', 'jong', 'trucs', 'rebels', 'creatief', 'vrij', 'cool', 'individueel', 'stijlvol', 'durven'],
  'parkour': ['stedelijk', 'vrijheid', 'atletisch', 'creatief', 'gevaarlijk', 'indrukwekkend', 'behendig', 'durven', 'vloeiend', 'spectaculair'],
  'crossfit': ['intens', 'gemeenschap', 'uitdagend', 'gevarieerd', 'competitief', 'transformerend', 'veeleisend', 'ondersteunend', 'resultaten', 'toewijding'],
  'triatlon': ['uithoudingsvermogen', 'uitdagend', 'compleet', 'veeleisend', 'overgangen', 'uitputtend', 'indrukwekkend', 'vastberaden', 'veelzijdig', 'elite'],
  'marathon': ['uithoudingsvermogen', 'mentaal', 'prestatie', 'uitdagend', 'menigte', 'emotioneel', 'persoonlijk', 'inspirerend', 'slopend', 'bevredigend'],
  'tienkamp': ['compleet', 'veelzijdig', 'veeleisend', 'atletisch', 'indrukwekkend', 'uitputtend', 'uitdagend', 'elite', 'vastberaden', 'bewonderenswaardig'],
  'vijfkamp': ['gevarieerd', 'militair', 'veeleisend', 'compleet', 'uitdagend', 'historisch', 'veelzijdig', 'atletisch', 'indrukwekkend', 'elite'],
  'biatlon': ['winter', 'contrasterend', 'veeleisend', 'precisie', 'uithoudingsvermogen', 'uniek', 'uitdagend', 'scandinavisch', 'atletisch', 'gefocust'],
  'taekwondo': ['trappen', 'koreaans', 'discipline', 'respect', 'atletisch', 'precies', 'krachtig', 'ceremonieel', 'competitief', 'gefocust'],
  'aikido': ['harmonie', 'vloeiend', 'defensief', 'spiritueel', 'vredig', 'filosofisch', 'omleiden', 'elegant', 'cirkelvormig', 'zen'],
  'sumo': ['japans', 'ritueel', 'traditioneel', 'zwaar', 'ceremonieel', 'spiritueel', 'krachtig', 'heilig', 'oud', 'eerbaar'],
  'kickboksen': ['intens', 'krachtig', 'veeleisend', 'atletisch', 'agressief', 'gedisciplineerd', 'explosief', 'uitdagend', 'competitief', 'taai'],
  'capoeira': ['dans', 'braziliaans', 'ritmisch', 'cultureel', 'acrobatisch', 'artistiek', 'muzikaal', 'vloeiend', 'historisch', 'gemeenschappelijk'],
  'darten': ['precisie', 'kroeg', 'sociaal', 'concentratie', 'kalm', 'ontspannen', 'strategisch', 'competitief', 'traditioneel', 'gefocust'],
  'biljart': ['strategisch', 'kalm', 'sociaal', 'geometrisch', 'precies', 'elegant', 'ontspannen', 'verfijnd', 'berekend', 'geduldig'],
  'bowlen': ['sociaal', 'casual', 'leuk', 'familie', 'competitief', 'nostalgisch', 'retro', 'vriendelijk', 'recreatief', 'vermakelijk'],
  'schaken': ['strategisch', 'intellectueel', 'stil', 'geduldig', 'oud', 'berekend', 'mentaal', 'competitief', 'absorberend', 'tijdloos'],
  'poker': ['strategisch', 'psychologisch', 'risicovol', 'sociaal', 'spanning', 'bluffen', 'berekenend', 'competitief', 'zenuwslopend', 'spannend'],

  // === OBJECTS (Voorwerpen - 50 words) ===
  'telefoon': ['verslavend', 'communicatie', 'constant', 'persoonlijk', 'afleiding', 'essentieel', 'verbonden', 'angst', 'gemak', 'meldingen'],
  'computer': ['werk', 'verbinding', 'informatie', 'modern', 'scherm', 'essentieel', 'frustrerend', 'krachtig', 'productiviteit', 'digitaal'],
  'televisie': ['entertainment', 'passief', 'familie', 'nieuws', 'bank', 'ontspanning', 'afleiding', 'avond', 'streamen', 'troost'],
  'klok': ['routine', 'punctueel', 'spanning', 'cadeau', 'elegant', 'tikken', 'druk', 'decoratief', 'voorbijgaand', 'herinnering'],
  'lamp': ['sfeer', 'nachtelijk', 'lezen', 'decoratief', 'warm', 'gezellig', 'zacht', 'intiem', 'essentieel', 'troost'],
  'stoel': ['rust', 'gewoon', 'kantoor', 'wachten', 'vergadering', 'comfort', 'essentieel', 'ondersteuning', 'dagelijks', 'alomtegenwoordig'],
  'tafel': ['samen', 'familie', 'werk', 'eten', 'centraal', 'essentieel', 'sociaal', 'vergaderingen', 'dagelijks', 'basis'],
  'bed': ['rust', 'dromen', 'comfort', 'intiem', 'zacht', 'toevlucht', 'essentieel', 'vredig', 'rustplaats', 'gezellig'],
  'spiegel': ['reflectie', 'ijdelheid', 'waarheid', 'ochtend', 'decoratief', 'eerlijkheid', 'zelf', 'onthullend', 'essentieel', 'routine'],
  'raam': ['licht', 'buiten', 'lucht', 'kijken', 'ontsnappen', 'uitzichten', 'vers', 'verbinding', 'kader', 'openheid'],
  'deur': ['kans', 'privacy', 'ingang', 'sluiten', 'veiligheid', 'overgang', 'welkom', 'barrière', 'bescherming', 'drempel'],
  'trap': ['inspanning', 'omhoog', 'etappes', 'gebouw', 'beweging', 'vooruitgang', 'overgang', 'verbinden', 'klimmen', 'routine'],
  'lift': ['wachten', 'klein', 'snel', 'ongemakkelijk', 'modern', 'handig', 'afgesloten', 'verticaal', 'snel', 'onpersoonlijk'],
  'fiets': ['vrijheid', 'beweging', 'ecologisch', 'kindertijd', 'balans', 'onafhankelijkheid', 'gezond', 'simpel', 'nostalgisch', 'duurzaam'],
  'auto': ['onafhankelijkheid', 'reizen', 'verkeer', 'vrijheid', 'duur', 'essentieel', 'status', 'mobiliteit', 'comfort', 'vervuiling'],
  'vliegtuig': ['afstand', 'snel', 'zenuwen', 'hoogte', 'raampje', 'reizen', 'opwinding', 'verbinding', 'avontuur', 'gemak'],
  'boot': ['langzaam', 'horizon', 'zeeziek', 'vakantie', 'romantisch', 'vredig', 'avontuurlijk', 'vrijheid', 'ontspannend', 'ontsnappen'],
  'trein': ['reis', 'landschap', 'punctueel', 'nostalgisch', 'ritme', 'romantisch', 'comfortabel', 'efficiënt', 'ontspannend', 'traditioneel'],
  'motor': ['vrijheid', 'adrenaline', 'jong', 'snel', 'wind', 'rebels', 'gevaarlijk', 'opwindend', 'onafhankelijk', 'cool'],
  'skateboard': ['jong', 'stedelijk', 'trucs', 'rebels', 'balans', 'cool', 'creatief', 'vrijheid', 'straat', 'individueel'],
  'gitaar': ['romantisch', 'kampvuur', 'expressief', 'leren', 'akoestisch', 'emotioneel', 'creatief', 'nostalgisch', 'persoonlijk', 'draagbaar'],
  'piano': ['elegant', 'klassiek', 'toewijding', 'groot', 'expressief', 'verfijnd', 'emotioneel', 'tijdloos', 'indrukwekkend', 'mooi'],
  'drumstel': ['ritme', 'primitief', 'feest', 'energie', 'tribaal', 'krachtig', 'oer', 'opwindend', 'luid', 'basis'],
  'viool': ['emotioneel', 'klassiek', 'moeilijk', 'orkest', 'elegant', 'mooi', 'expressief', 'verfijnd', 'delicaat', 'gepassioneerd'],
  'fluit': ['zoet', 'oud', 'school', 'adem', 'melodie', 'zachtaardig', 'etherisch', 'delicaat', 'vredig', 'traditioneel'],
  'camera': ['herinneringen', 'moment', 'reizen', 'observeren', 'vastleggen', 'creatief', 'kostbaar', 'documenteren', 'artistiek', 'bewaren'],
  'boek': ['ontsnappen', 'kennis', 'fantasie', 'rustig', 'oud', 'wijsheid', 'reis', 'troost', 'ontdekking', 'tijdloos'],
  'potlood': ['ideeën', 'school', 'uitgummen', 'eenvoudig', 'creatief', 'basis', 'schetsen', 'tijdelijk', 'bescheiden', 'essentieel'],
  'schaar': ['knippen', 'precies', 'knutselen', 'gevaarlijk', 'school', 'nuttig', 'scherp', 'essentieel', 'praktisch', 'voorzichtig'],
  'paraplu': ['bescherming', 'regen', 'vergeten', 'stad', 'grijs', 'essentieel', 'gedeeld', 'romantisch', 'praktisch', 'schuilplek'],
  'koffer': ['reizen', 'avontuur', 'pakken', 'zwaar', 'georganiseerd', 'reizen', 'vertrek', 'verwachting', 'herinneringen', 'draagbaar'],
  'rugzak': ['avontuur', 'praktisch', 'student', 'reizen', 'vrijheid', 'casual', 'essentieel', 'wandelen', 'handig', 'jeugd'],
  'handtas': ['essentieel', 'persoonlijk', 'georganiseerd', 'mode', 'vrouwelijk', 'praktisch', 'schat', 'identiteit', 'chaos', 'geheimen'],
  'portemonnee': ['essentieel', 'persoonlijk', 'identiteit', 'veiligheid', 'georganiseerd', 'simpel', 'mannelijk', 'praktisch', 'slank', 'belangrijk'],
  'sleutel': ['toegang', 'veiligheid', 'belangrijk', 'klein', 'essentieel', 'verantwoordelijkheid', 'verloren', 'symbolisch', 'openen', 'ontsluiten'],
  'hangslot': ['veiligheid', 'bescherming', 'vertrouwen', 'gesloten', 'essentieel', 'symbolisch', 'vergrendeld', 'beveiligen', 'privé', 'stevig'],
  'zaklamp': ['duisternis', 'noodgeval', 'essentieel', 'kamperen', 'nuttig', 'leidend', 'verkennend', 'draagbaar', 'praktisch', 'geruststellen'],
  'kompas': ['richting', 'navigatie', 'avontuur', 'verloren', 'leiding', 'essentieel', 'verkennend', 'traditioneel', 'betrouwbaar', 'simpel'],
  'verrekijker': ['kijken', 'ver', 'natuur', 'nieuwsgierig', 'observeren', 'avontuur', 'verkennend', 'gedetailleerd', 'safari', 'vogelen'],
  'telescoop': ['sterren', 'verwondering', 'ver', 'ontdekking', 'kosmisch', 'nieuwsgierig', 'wetenschappelijk', 'dromen', 'verkennend', 'nachtelijk'],
  'microscoop': ['klein', 'wetenschappelijk', 'ontdekking', 'nieuwsgierig', 'detail', 'laboratorium', 'verkennend', 'onthullend', 'precies', 'educatief'],
  'thermometer': ['koorts', 'gezondheid', 'precisie', 'essentieel', 'zorgen', 'diagnose', 'nauwkeurig', 'medisch', 'temperatuur', 'monitoren'],
  'stethoscoop': ['luisteren', 'medisch', 'vertrouwen', 'professioneel', 'diagnose', 'intiem', 'essentieel', 'klinisch', 'geruststellen', 'bekwaam'],
  'spuit': ['medisch', 'angst', 'nodig', 'scherp', 'klinisch', 'precies', 'essentieel', 'genezend', 'angst', 'professioneel'],
  'scalpel': ['precies', 'scherp', 'medisch', 'chirurgisch', 'delicaat', 'professioneel', 'bekwaam', 'essentieel', 'schoon', 'exact'],
  'hamer': ['bouwen', 'kracht', 'essentieel', 'basis', 'constructie', 'krachtig', 'simpel', 'nuttig', 'fundamenteel', 'slaan'],
  'schroevendraaier': ['repareren', 'essentieel', 'basis', 'nuttig', 'praktisch', 'handig', 'draaien', 'simpel', 'fundamenteel', 'nodig'],
  'boor': ['kracht', 'bouwen', 'constructie', 'nuttig', 'professioneel', 'essentieel', 'efficiënt', 'luid', 'praktisch', 'modern'],
  'zaag': ['snijden', 'constructie', 'scherp', 'gevaarlijk', 'nuttig', 'bouwen', 'essentieel', 'krachtig', 'precies', 'professioneel'],
  'tang': ['grijpen', 'nuttig', 'essentieel', 'repareren', 'praktisch', 'veelzijdig', 'handig', 'sterk', 'fundamenteel', 'basis'],

  // === NATURE (Natuur - 50 words) ===
  'boom': ['schaduw', 'oud', 'groei', 'wortels', 'thuis', 'vredig', 'leven', 'wijsheid', 'schuilplek', 'eeuwig'],
  'bloem': ['cadeau', 'vluchtig', 'geur', 'lente', 'romantisch', 'delicaat', 'mooi', 'kleurrijk', 'vergankelijk', 'hoopvol'],
  'rivier': ['stromen', 'constant', 'grens', 'leven', 'reis', 'vredig', 'krachtig', 'eindeloos', 'verfrissend', 'kronkelend'],
  'meer': ['rustig', 'reflectie', 'diep', 'mysterieus', 'stilte', 'vredig', 'sereen', 'stil', 'verfrissend', 'rustig'],
  'oceaan': ['uitgestrekt', 'mysterieus', 'krachtig', 'horizon', 'diep', 'eindeloos', 'nederig makend', 'oud', 'levend', 'majestueus'],
  'bos': ['vrede', 'mysterieus', 'groen', 'toevlucht', 'oud', 'levend', 'heilig', 'schuilplek', 'betoverd', 'oer'],
  'jungle': ['dicht', 'vochtig', 'wild', 'geluiden', 'gevaarlijk', 'levend', 'exotisch', 'mysterieus', 'ongetemd', 'oer'],
  'woestijn': ['leeg', 'hitte', 'eenzaamheid', 'extreem', 'goud', 'eindeloos', 'hard', 'stil', 'spiritueel', 'transformerend'],
  'eiland': ['geïsoleerd', 'ontsnappen', 'tropisch', 'klein', 'paradijs', 'vredig', 'afgelegen', 'dromerig', 'exotisch', 'toevlucht'],
  'waterval': ['krachtig', 'lawaai', 'fris', 'majestueus', 'avontuur', 'verfrissend', 'mooi', 'indrukwekkend', 'eeuwig', 'dramatisch'],
  'regenboog': ['hoop', 'vluchtig', 'magisch', 'na de regen', 'kleuren', 'mooi', 'belofte', 'verwondering', 'vergankelijk', 'vreugdevol'],
  'wolk': ['zacht', 'vormen', 'wit', 'veranderend', 'dromen', 'drijvend', 'vredig', 'vluchtig', 'fantasierijk', 'zachtaardig'],
  'zon': ['energie', 'warmte', 'wakker', 'leven', 'helder', 'essentieel', 'krachtig', 'constant', 'hoopvol', 'vrolijk'],
  'maan': ['nachtelijk', 'romantisch', 'cycli', 'mysterieus', 'zilver', 'vredig', 'magisch', 'dromerig', 'reflecterend', 'eeuwig'],
  'ster': ['wens', 'ver', 'nachtelijk', 'helder', 'navigatie', 'dromen', 'eeuwig', 'fonkelend', 'hoopvol', 'magisch'],
  'regen': ['melancholie', 'reiniging', 'geluid', 'grijs', 'verfrissend', 'gezellig', 'vernieuwing', 'vredig', 'nostalgisch', 'romantisch'],
  'sneeuw': ['stilte', 'koud', 'wit', 'kerst', 'puur', 'vredig', 'magisch', 'transformerend', 'stil', 'maagdelijk'],
  'donder': ['angst', 'krachtig', 'waarschuwing', 'lawaai', 'storm', 'dramatisch', 'indrukwekkend', 'oer', 'onheilspellend', 'rommelend'],
  'bliksem': ['snel', 'gevaarlijk', 'helder', 'energie', 'vluchtig', 'krachtig', 'elektrisch', 'dramatisch', 'spectaculair', 'plotseling'],
  'tornado': ['verwoestend', 'draaiend', 'angst', 'krachtig', 'chaotisch', 'gevaarlijk', 'gewelddadig', 'onvoorspelbaar', 'dramatisch', 'angstaanjagend'],
  'aardbeving': ['angst', 'verwoestend', 'onvoorspelbaar', 'schudden', 'paniek', 'krachtig', 'plotseling', 'angstaanjagend', 'chaotisch', 'vernietigend'],
  'tsunami': ['verwoestend', 'gigantisch', 'paniek', 'kust', 'snel', 'angstaanjagend', 'krachtig', 'vernietigend', 'overweldigend', 'catastrofaal'],
  'gletsjer': ['oud', 'koud', 'langzaam', 'blauw', 'smelten', 'massief', 'eeuwig', 'majestueus', 'maagdelijk', 'bedreigd'],
  'noorderlicht': ['magisch', 'nachtelijk', 'noord', 'kleurrijk', 'vluchtig', 'dansend', 'mysterieus', 'etherisch', 'adembenemend', 'verwondering'],
  'zonsopgang': ['nieuw', 'hoop', 'vroeg', 'oranje', 'begin', 'vredig', 'mooi', 'veelbelovend', 'vers', 'inspirerend'],
  'zonsondergang': ['romantisch', 'oranje', 'vredig', 'einde', 'kijken', 'mooi', 'nostalgisch', 'gouden', 'sereen', 'reflecterend'],
  'koraal': ['kleurrijk', 'fragiel', 'onderwater', 'kolonie', 'beschermd', 'mooi', 'bedreigd', 'divers', 'delicaat', 'vitaal'],
  'zeewier': ['groen', 'glad', 'marien', 'voedsel', 'verward', 'gezond', 'drijvend', 'zout', 'nuttig', 'overvloedig'],
  'paddenstoel': ['donker', 'vochtig', 'mysterieus', 'bos', 'snel', 'verborgen', 'aards', 'herfst', 'magisch', 'nieuwsgierig'],
  'cactus': ['veerkrachtig', 'stekelig', 'droog', 'groen', 'eenzaam', 'overlever', 'geduldig', 'woestijn', 'taai', 'uniek'],
  'palmboom': ['tropisch', 'vakantie', 'ontspannend', 'exotisch', 'strand', 'paradijs', 'wiegend', 'iconisch', 'warm', 'dromerig'],
  'bamboe': ['snel', 'flexibel', 'aziatisch', 'sterk', 'duurzaam', 'veelzijdig', 'vredig', 'natuurlijk', 'elegant', 'zen'],
  'eik': ['sterk', 'oud', 'wijs', 'schaduw', 'traditioneel', 'majestueus', 'duurzaam', 'geworteld', 'nobel', 'historisch'],
  'den': ['groenblijvend', 'geurig', 'kerst', 'hoog', 'fris', 'winter', 'vredig', 'veerkrachtig', 'aromatisch', 'berg'],
  'wilg': ['sierlijk', 'huilend', 'romantisch', 'vredig', 'flexibel', 'poëtisch', 'zachtaardig', 'melancholisch', 'vloeiend', 'dromerig'],
  'orchidee': ['exotisch', 'delicaat', 'elegant', 'moeilijk', 'mooi', 'luxueus', 'verfijnd', 'kostbaar', 'verfijnd', 'zeldzaam'],
  'roos': ['romantisch', 'geurig', 'doornen', 'klassiek', 'mooi', 'symbolisch', 'gepassioneerd', 'elegant', 'tijdloos', 'kostbaar'],
  'tulp': ['lente', 'kleurrijk', 'hollands', 'elegant', 'simpel', 'vrolijk', 'fris', 'delicaat', 'mooi', 'hoopvol'],
  'zonnebloem': ['vrolijk', 'hoog', 'volgend', 'geel', 'blij', 'helder', 'optimistisch', 'zomer', 'warm', 'vreugdevol'],
  'madeliefje': ['simpel', 'onschuldig', 'vrolijk', 'gewoon', 'fris', 'puur', 'bescheiden', 'lief', 'nostalgisch', 'vriendelijk'],
  'vallei': ['vredig', 'groen', 'beschut', 'vruchtbaar', 'verborgen', 'sereen', 'pastoraal', 'beschermd', 'weelderig', 'idyllisch'],
  'kloof': ['diep', 'dramatisch', 'oud', 'indrukwekkend', 'uitgestrekt', 'geologisch', 'majestueus', 'uitgehouwen', 'adembenemend', 'gelaagd'],
  'weide': ['vredig', 'bloemen', 'zomer', 'simpel', 'pastoraal', 'idyllisch', 'open', 'fris', 'nostalgisch', 'zachtaardig'],
  'moeras': ['troebel', 'mysterieus', 'vochtig', 'gevaarlijk', 'levend', 'dicht', 'mistig', 'oer', 'griezelig', 'verborgen'],
  'mangrove': ['kust', 'beschermend', 'vitaal', 'complex', 'uniek', 'verweven', 'beschuttend', 'tropisch', 'essentieel', 'ecosysteem'],
  'toendra': ['koud', 'kaal', 'extreem', 'uitgestrekt', 'hard', 'bevroren', 'afgelegen', 'maagdelijk', 'sober', 'stil'],
  'savanne': ['uitgestrekt', 'gouden', 'afrikaans', 'dieren', 'open', 'droog', 'eindeloos', 'wild', 'majestueus', 'dramatisch'],
  'steppe': ['uitgestrekt', 'leeg', 'wind', 'grasland', 'eindeloos', 'open', 'hard', 'nomadisch', 'sober', 'winderig'],
  'oase': ['toevlucht', 'paradijs', 'onverwacht', 'leven', 'verlichting', 'groen', 'kostbaar', 'wonderbaarlijk', 'hoop', 'overleven']
};
